Scrivito/scrivito-portal-app

src/Widgets/DataIconConditionWidget/DataIconConditionWidgetClass.ts, src/Widgets/DataIconConditionWidget/DataIconConditionWidgetEditingConfig.ts, src/Widgets/DataIconWidget/DataIconWidgetClass.ts, src/Widgets/DataIconWidget/DataIconWidgetComponent.tsx, src/Widgets/DataIconWidget/DataIconWidgetEditingConfig.ts
Working copy: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://simpler-dataiconwidget.scrivito-portal-app.pages.dev/quotes-f7da3de531e46fe9?_scrivito_workspace_id=o3c92e8bfea6814b&_scrivito_display_mode=view
=> Simpler DataIconWidget

src/Components/NotFoundErrorPage.tsx, src/Widgets/DownloadCardWidget/DownloadCardWidgetClass.ts, src/Widgets/DownloadCardWidget/DownloadCardWidgetComponent.tsx, src/Widgets/DownloadCardWidget/DownloadCardWidgetEditingConfig.ts
Partly reverts https://github.com/Scrivito/scrivito-portal-app/pull/134.
Content changes: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://simpler-downloadcardwidget-a.scrivito-portal-app.pages.dev/quote-details-0092ff67875b69f8?_scrivito_workspace_id=j9345dd0ba4bda5b&_scrivito_display_mode=diff
=> Simpler DownloadCardWidget again

src/Widgets/IconContainerWidget/IconContainerWidgetComponent.tsx
=> IconContainerWidget bugfix: Use key on correct position.

src/Widgets/ImageWidget/ImageWidgetClass.ts, src/Widgets/ImageWidget/ImageWidgetComponent.tsx
=> ImageWidget: imageFromDataItem can also use Scrivito binaries

src/Widgets/DataFormDeleteButtonWidget/DataFormDeleteButtonWidgetClass.ts, src/Widgets/DataFormDeleteButtonWidget/DataFormDeleteButtonWidgetComponent.tsx, src/Widgets/DataFormDeleteButtonWidget/DataFormDeleteButtonWidgetEditingConfig.ts
* Styling option
* Confirmation option
* Redirect option
* Notice for editor which item will be deleted.
=> Improved DataFormDeleteButtonWidget

src/Data/CartItem/Cart.ts, src/Data/CartItem/CartItemDataClass.ts, src/Data/CartItem/CartItemEditingConfig.ts, src/Objs/Product/ProductComponent.tsx, src/Widgets/CheckoutButtonWidget/CheckoutButtonWidgetClass.ts, src/Widgets/CheckoutButtonWidget/CheckoutButtonWidgetComponent.tsx, src/Widgets/CheckoutButtonWidget/CheckoutButtonWidgetEditingConfig.ts, src/Widgets/DataListWidget/DataListWidgetComponent.tsx, src/Widgets/NavigationWidget/NavigationWidgetClass.ts, src/Widgets/NavigationWidget/NavigationWidgetEditingConfig.ts, src/Widgets/NavigationWidget/SubComponents/MetaNavigation.tsx, src/utils/provideLocalStorageDataClass.ts
Content: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://cartitem.scrivito-portal-app.pages.dev/products-749ee4e15707e4ff?_scrivito_workspace_id=h5c8efa927a78d2f&_scrivito_display_mode=view
=> Shopping Cart

src/Widgets/DataFormInputFieldWidget/DataFormInputFieldWidgetClass.ts, src/Widgets/DataFormInputFieldWidget/DataFormInputFieldWidgetComponent.tsx, src/Widgets/DataFormInputFieldWidget/DataFormInputFieldWidgetEditingConfig.ts, src/Widgets/DataFormSubmitButtonWidget/DataFormSubmitButtonWidgetClass.ts, src/Widgets/DataFormSubmitButtonWidget/DataFormSubmitButtonWidgetComponent.tsx, src/Widgets/DataFormSubmitButtonWidget/DataFormSubmitButtonWidgetEditingConfig.ts
* DataFormSubmitButton provides the same size and alignment options as the ButtonWidget.
* DataFormInputField can also handle email and phone numbers.
=> Improved DataForm widgets

src/Data/CurrentUser/CurrentUserDataEditingConfig.ts, src/Data/CurrentUser/CurrentUserDataItem.ts
Content: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://neoletter-profile.scrivito-portal-app.pages.dev/my-profile-0e84d1e469f7cfac?_scrivito_workspace_id=gcfdd84e5cb99e01&_scrivito_display_mode=view
=> Neoletter profile

src/Widgets/DataFormSubmitButtonWidget/DataFormSubmitButtonWidgetEditingConfig.ts
Content: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://betterreset.scrivito-portal-app.pages.dev/?_scrivito_workspace_id=v7293a709d8b9745&_scrivito_display_mode=diff
=> DataFormSubmitButton: Less confusion terms: reset => cancel

src/Data/CartItem/Cart.ts, src/Objs/Product/ProductComponent.tsx, src/utils/provideLocalStorageDataClass.ts
Discovered during the Hackathon by @patrykostrowski95.
This PR resolves the following bugreport.
How to reproduce:
* Visit edit.scrivito.com/localhost:8080 in Chrome Incognito mode
_Expected_
Site renders
_Actual_
The error component is show with the following stacktrace:
```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
at restoreRecord (http://localhost:8080/src/utils/provideLocalStorageDataClass.ts:45:22)
at index (http://localhost:8080/src/utils/provideLocalStorageDataClass.ts:9:32)
at IdBatchCollection.<anonymous> (http://localhost:8080/node_modules/.vite/deps/scrivito.js?v=920c973e:14127:42)
at Generator.next (<anonymous>)
at http://localhost:8080/node_modules/.vite/deps/scrivito.js?v=920c973e:14086:77
at new …
```
=> Bugfix localStorage

src/Widgets/CheckoutButtonWidget/CheckoutButtonWidgetComponent.tsx, src/Widgets/DataFormDeleteButtonWidget/DataFormDeleteButtonWidgetComponent.tsx, src/Widgets/DataFormSubmitButtonWidget/DataFormSubmitButtonWidgetComponent.tsx, src/Widgets/FormButtonWidget/FormButtonWidgetComponent.tsx
Previously some buttons allowed to be inplace edited. During the hackathon this created some confusion.
=> Buttons will now always work - regardless of mode

src/Data/CurrentUser/CurrentUserDataEditingConfig.ts, src/Data/CurrentUser/CurrentUserDataItem.ts
This is automatically shown in the top navigation - if logged in.
=> Added picture to CurrentUser

src/config/scrivito.ts
See https://www.scrivito.com/automatic-type-conversions-0cff08a7795d5d3c for details about this flag
=> Make use of new "autoConvertAttributes" option

src/Data/CartItem/Cart.ts, src/Widgets/NavigationWidget/SubComponents/MetaNavigation.tsx
=> Cart icon: Show a batch counter with number of items

src/Widgets/DataFormOptionsWidget/DataFormOptionsWidgetClass.ts, src/Widgets/DataFormOptionsWidget/DataFormOptionsWidgetComponent.tsx, src/Widgets/DataFormOptionsWidget/DataFormOptionsWidgetEditingConfig.ts, src/Widgets/DataIconWidget/DataIconWidgetComponent.tsx
* DataIconWidget handles missing data better
* DataFormOptions allows to provide default option
=> Improved Data Widgets

package-lock.json, package.json, src/Widgets/DataLabelWidget/DataLabelWidgetClass.ts, src/Widgets/DataLabelWidget/DataLabelWidgetComponent.tsx, src/Widgets/DataLabelWidget/DataLabelWidgetEditingConfig.ts, src/Widgets/DataLabelWidget/RelativeDate.tsx
For now it only supports "relative" dates. More datetime options will probably come in the future.
For dates less then a month ago it will show a relative date. For dates older then a month it will show day and month. For all other dates it will show day, month and year.
=> DataLabelWidget: Add "datetime" option

src/Widgets/DataLabelWidget/DataLabelWidgetClass.ts, src/Widgets/DataLabelWidget/DataLabelWidgetComponent.tsx, src/Widgets/DataLabelWidget/DataLabelWidgetEditingConfig.ts
It's not really useful for the editor to have to pick the currency every time the value is shown.
=> DataLabelWidget: Hard-code currency to EUR for now.

src/Data/CurrentUser/CurrentUserDataEditingConfig.ts, src/Data/CurrentUser/CurrentUserDataItem.ts, src/Data/Ticket/TicketDataClass.ts, src/Data/Ticket/TicketEditingConfig.ts, src/Data/TicketMessage/TicketMessageDataClass.ts, src/Data/TicketMessage/TicketMessageEditingConfig.ts, src/Widgets/NavigationWidget/SubComponents/CurrentUserDropdown.tsx
Content: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://fake-tickets.scrivito-portal-app.pages.dev/tickets-125f0003cf11c725?_scrivito_workspace_id=gb49994784908a54&_scrivito_display_mode=view
=> Fake tickets + Improvements

src/Objs/ProductsOverview/ProductOverviewLayoutComponent.tsx, src/Objs/SubnavigationOverview/SubnavigationOverviewLayoutComponent.tsx, src/Widgets/ButtonWidget/ButtonWidgetComponent.tsx, src/Widgets/ColumnContainerWidget/ColumnsEditorTab.scss, src/Widgets/SearchResultsWidget/SearchResult.tsx, src/assets/stylesheets/index.scss
z-0 deleted + @include transition translated to native CSS + inline styles deleted for buttons, sections + if btn empty it displays message
=> Less TODOs

package-lock.json, package.json, src/Widgets/DataFormNumberWidget/DataFormNumberWidgetEditingConfig.tsx
See https://www.scrivito.com/scrivito-js-sdk-1-39-0-rc-1-released-706db9b3b205e96a for all the nice good things.
=> Scrivito 1.39.0-rc1

src/Data/CartItem/Cart.ts
The checkout experience is still not perfect, but better than before.
=> Cart creates ticket with request

src/Objs/Product/ProductComponent.tsx, src/Objs/Product/ProductPreviewComponent.tsx, src/Objs/SubnavigationOverview/SubnavigationOverviewLayoutComponent.tsx, src/Widgets/AddressWidget/AddressWidgetComponent.tsx, src/Widgets/DataLabelWidget/DataLabelWidgetComponent.tsx, src/Widgets/DownloadCardWidget/DownloadCardWidgetComponent.tsx
Some parts of https://github.com/Scrivito/scrivito-portal-app/pull/262 by @agessler .
=> First part of Rebrush2

src/Objs/Product/ProductComponent.tsx
Some parts of https://github.com/Scrivito/scrivito-portal-app/pull/262 by @agessler .
=> Second part of Rebrush2

src/Widgets/PersonCardWidget/PersonCardWidgetClass.ts, src/Widgets/PersonCardWidget/PersonCardWidgetComponent.tsx, src/Widgets/PersonCardWidget/PersonCardWidgetEditingConfig.ts
It is no longer needed to place it in the correct "DataListWidget"
Content: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://improvedpersoncardwidget.scrivito-portal-app.pages.dev/my-tynacoon-59274260f223b65f?_scrivito_workspace_id=i5f8016e9435ba0e&_scrivito_display_mode=view
=> Simplified rendering of PersonCardWidget

src/config/scrivito.ts
Option available with Scrivito 1.35.0 (see https://edit-beta.scrivito.com/8f93962411449dab9b82023285404d2e~https://www.scrivito.com/js-sdk/configure#Options
=> Add correct extensionsUrl for multi-tenancy

src/Objs/SubnavigationOverview/SubnavigationOverviewLayoutComponent.tsx, src/Widgets/DownloadCardWidget/DownloadCardWidgetComponent.tsx, src/Widgets/PersonCardWidget/PersonCardWidgetComponent.tsx, src/assets/stylesheets/index.scss
Download and Person card get no color adaption in any environment + correct btn sizes + headline color fixes
@apepper when merged we need to adapt some btn sizes in many pages in tenant
=>  no color adaption  + btn sizes + headline color fixes

package-lock.json, package.json
With #298 we're using the latest boostrap version.
=> Upgrade sass to the latest version

src/Data/Message/MessageDataClass.ts, src/Data/Message/MessageEditingConfig.ts
New content: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://ticket-message-to-message.scrivito-portal-app.pages.dev/my-tynacoon-59274260f223b65f?_scrivito_workspace_id=ofefb4262dff7af5&_scrivito_display_mode=view
=> Moved "TicketMessage" to "Message"

src/Widgets/DataFormBooleanWidget/DataFormBooleanWidgetComponent.tsx, src/Widgets/DataFormInputFieldWidget/DataFormInputFieldWidgetComponent.tsx, src/Widgets/DataFormNumberWidget/DataFormNumberWidgetComponent.tsx, src/Widgets/DataFormOptionsWidget/DataFormOptionsWidgetComponent.tsx, src/Widgets/DataFormUploadWidget/DataFormUploadWidgetComponent.tsx, src/Widgets/FormCheckboxWidget/FormCheckboxWidgetComponent.tsx, src/Widgets/FormInputFieldWidget/FormInputFieldWidgetComponent.tsx
The removed code was a workaround for a Scrivito in-place editing issue fixed in 1.34.0.
=> Simplify htmlFor

src/Data/CurrentUser/CurrentUserDataEditingConfig.ts, src/Data/CurrentUser/CurrentUserDataItem.ts, src/Data/User/UserDataClass.ts
The data for the current user should come mainly from the neoletter profile service. Only the e-mail and profile picture should be taken from IAM. Only very limited information should be taken from Pisa (actual code for that in a different branch).
Needs content changes: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://neoletter-profile-wins.scrivito-portal-app.pages.dev/my-profile-0e84d1e469f7cfac?current_user_id=0&_scrivito_workspace_id=u6ea13b19f0b6fc9&_scrivito_display_mode=view
=> Neoletter profile wins

src/Widgets/SearchResultsWidget/SearchResult.tsx, src/Widgets/SearchResultsWidget/SearchResultsWidgetComponent.tsx, src/assets/stylesheets/index.scss, src/assets/stylesheets/theme/box-comment.scss
under a link only in useful area, selection color update, text-multiline fix, comment avatar size fix, search result btn color fix
=> FIX for underline, selection, text-multiline, comment, btn

src/Data/GeneralMarketingConsent/GeneralMarketingConsentDataItem.ts, src/Data/Subscription/SubscriptionDataClass.ts
No longer needed according to https://infopark.slack.com/archives/C04TN8LJA/p1708428639405689.
=> Remove neoletter workarounds

src/assets/stylesheets/index.scss
As discussed in https://github.com/Scrivito/scrivito-portal-app/pull/302#discussion_r1492509298.
See it live on https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://fix-nested-links.scrivito-portal-app.pages.dev/colors?_scrivito_workspace_id=q6a733838df01858&_scrivito_display_mode=view
=> [design] Fix links in nested card widgets

src/Widgets/DataFormBooleanWidget/DataFormBooleanWidgetComponent.tsx
Live-Demo: https://dataformbooleanwidget-lower.scrivito-portal-app.pages.dev/subscriptions
=> DataFormBooleanWidget: Grey out unselected toggled just a bit

src/Widgets/DataMessageWidget/DataMessageWidgetComponent.tsx, src/assets/stylesheets/theme/box-comment.scss
Also moved content from CSS to react.
=> DataMessageWidget bugfix

src/Widgets/DataFormBooleanWidget/DataFormBooleanWidgetComponent.tsx, src/Widgets/DataFormInputFieldWidget/DataFormInputFieldWidgetComponent.tsx, src/Widgets/DataFormNumberWidget/DataFormNumberWidgetComponent.tsx, src/Widgets/DataFormOptionsWidget/DataFormOptionsWidgetComponent.tsx
Discovered while clicking on the label of a topic (e.g. the second one).
=> Bugfix data form ids

src/assets/stylesheets/index.scss
Fix for https://trello.com/c/n5l4xLwL/93-high-contrast-mode
=> uglify css for high contrast mode

src/Widgets/DataLabelWidget/DataLabelWidgetClass.ts, src/Widgets/DataLabelWidget/DataLabelWidgetComponent.tsx, src/Widgets/DataLabelWidget/DataLabelWidgetEditingConfig.ts
Motivation: The upcoming "event" will have a `url` field. With this option the URL becomes clickable.
=> DataLabelWidget: Add "link" format

src/Widgets/DataLabelWidget/DataLabelWidgetEditingConfig.ts
Follow up of https://github.com/Scrivito/scrivito-portal-app/pull/331#discussion_r1523356327.
=> Avoid "isString" depedency on lodash-es

src/Data/Gdpr/GdprDataClass.ts, src/Data/Gdpr/GdprEditingConfig.ts
Needs content: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://gdpr.scrivito-portal-app.pages.dev/my-profile?_scrivito_workspace_id=k787799d6a7e4005&_scrivito_display_mode=view
=> GDPR DataClass

src/Data/Ticket/TicketDataClass.ts
=> Add an example ticket ↔ service object association

src/assets/stylesheets/scrivitoEditing.scss, src/main.tsx
Based on an internal discussion here: https://infopark.slack.com/archives/G01F5J9817Z/p1712222151294679?thread_ts=1712220545.316979&cid=G01F5J9817Z
=> Better in-place editing feedback for uppercased design elements

src/Widgets/AddressWidget/AddressWidgetClass.ts, src/Widgets/AddressWidget/AddressWidgetComponent.tsx, src/Widgets/AddressWidget/AddressWidgetEditingConfig.ts
https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://dave-german.scrivito-portal-app.pages.dev/de?_scrivito_workspace_id=p5bcc7f596b13012&_scrivito_display_mode=diff
=> Make address widget labels editable

src/Widgets/NavigationWidget/NavigationWidgetClass.ts, src/Widgets/NavigationWidget/NavigationWidgetComponent.tsx, src/Widgets/NavigationWidget/NavigationWidgetEditingConfig.ts, src/Widgets/NavigationWidget/SubComponents/MainNavigation.tsx, src/Widgets/NavigationWidget/SubComponents/SearchBox.tsx, src/Widgets/SearchResultsWidget/SearchResult.tsx, src/Widgets/SearchResultsWidget/SearchResultsWidgetClass.ts, src/Widgets/SearchResultsWidget/SearchResultsWidgetComponent.tsx, src/Widgets/SearchResultsWidget/SearchResultsWidgetEditingConfig.ts
Same working copy as #356 
https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://dave-german-search.scrivito-portal-app.pages.dev/de?_scrivito_workspace_id=p5bcc7f596b13012&_scrivito_display_mode=diff
=> Make search-related labels and headlines editable

src/Widgets/DataColumnListWidget/DataColumnListWidgetComponent.tsx, src/Widgets/DataEmptyWidget/DataEmptyWidgetComponent.tsx, src/Widgets/DataFormContainerWidget/DataFormContainerWidgetComponent.tsx, src/Widgets/DataPersonCardWidget/DataPersonCardWidgetComponent.tsx, src/Widgets/DataWidget/DataWidgetComponent.tsx
There is always a dataScope, e.g. a empty one.
Cleanup from https://github.com/Scrivito/scrivito-portal-app/pull/360.
=> Remove obsolete !dataScope tests

src/Objs/Homepage/HomepageLayoutComponent.tsx, src/Objs/Redirect/RedirectComponent.tsx, src/Objs/Redirect/RedirectObjClass.ts, src/Widgets/NavigationWidget/SubComponents/Brand.tsx, src/Widgets/NavigationWidget/SubComponents/MetaNavigation.tsx, src/config/scrivitoContentBrowser.ts, src/utils/getSitePortalOverviewPage.ts
Follow up of https://github.com/Scrivito/scrivito-portal-app/pull/348.
Closes #367.
Idea by @dcsaszar in https://github.com/Scrivito/scrivito-portal-app/pull/367#discussion_r1570342507
=> Use protected content inside portal - follow up 2

src/dumpContent.ts
Sorry for commit message typo.
=> Update content dump to new dump format

src/Objs/Product/ProductComponent.tsx, src/Objs/ProductCategory/ProductCategoryComponent.tsx, src/Objs/ProductCategory/ProductCategoryEditingConfig.ts, src/Objs/ProductCategory/ProductCategoryObjClass.ts
Clear old content: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://dave-hardcode-category-local.scrivito-portal-app.pages.dev/en/filling-lines-888338d8ca9cb8da?_scrivito_workspace_id=u530335745c01ab7&_scrivito_display_mode=diff
=> Hardcode product category localizers

src/Data/Document/Pisa/pisaDocumentDataClass.ts, src/Data/Event/Pisa/pisaEventDataClass.ts, src/Data/Gdpr/Pisa/pisaGdprDataClass.ts, src/Data/Order/Pisa/pisaOrderDataClass.ts, src/Data/Quote/Pisa/pisaQuoteDataClass.ts, src/Data/ServiceObject/Pisa/pisaServiceObjectDataClass.ts, src/Widgets/NavigationWidget/SubComponents/LanguageSwitch.tsx, src/utils/currentLanguage.ts
Plus: Language switch reloads the app.
=> Accept-Language for some pisa data classes.

src/Data/neoletterClient.ts, src/Data/pisaClient.ts, src/Data/toClientParams.ts
See https://github.com/infopark/scrivito_js/pull/10872
=> onDevSdk: adapt to current master

src/Widgets/LogInButtonWidget/LogInButtonWidgetEditingConfig.ts
Follow up of https://github.com/Scrivito/scrivito-portal-app/pull/401#discussion_r1594713226
=> Adjusted title of LogInButtonWidget

src/Widgets/NavigationWidget/SubComponents/CurrentUserDropdown.tsx
Diff best viewed without whitespace changes
=> CurrentUserMenu: Show a loading spinner

headers.config.ts, src/config/scrivito.ts
=> Allow to be framed by Scrivito preview deployments

src/Components/ErrorBoundary.tsx, src/Widgets/DataIconWidget/DataIconWidgetComponent.tsx
Based on my review findings in #414
=> Simplify code

src/Data/User/UserEditingConfig.ts
=> User: Extended editing config with existing attributes

src/Widgets/DataIconWidget/DataIconWidgetComponent.tsx, src/Widgets/DataLabelWidget/DataLabelWidgetComponent.tsx
=> Provide german version for "N/A" text

src/Data/OrderRequest/LocalStorage/localStorageOrderRequestDataClass.ts, src/Data/OrderRequest/OrderRequestDataClass.ts, src/Data/OrderRequest/OrderRequestEditingConfig.ts, src/Data/OrderRequest/Pisa/pisaOrderRequestDataClass.ts
Backport of https://github.com/Scrivito/scrivito-portal-app/pull/421.
=> demo3 backport: Add OrderRequest data class

src/Widgets/DataColumnListWidget/DataColumnListWidgetComponent.tsx, src/Widgets/DataWidget/DataWidgetComponent.tsx
=> Remove usage of decommissioned "getError()" function.

src/Widgets/CardWidget/CardWidgetComponent.tsx, src/Widgets/CardWidget/CardWidgetEditingConfig.ts
The regular page background color is light-grey since the "recoloring"
=> CardWidget: Default color now white

src/Widgets/DataImageWidget/DataImageWidgetComponent.tsx
Follow-up of #430. See https://github.com/Scrivito/scrivito-portal-app/pull/430#pullrequestreview-2090950757.
=> DataImageWidget: More empty alt tags

src/Data/CartItem/Cart.ts, src/Data/Opportunity/LocalStorage/localStorageOpportunityDataClass.ts, src/Data/Opportunity/OpportunityDataClass.ts, src/Data/Opportunity/OpportunityEditingConfig.ts, src/Data/Opportunity/Pisa/pisaOpportunityDataClass.ts
https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://dave-opp.scrivito-portal-app.pages.dev/en/cart-a8ede3121df9e2f6?_scrivito_workspace_id=of94e4b23aebc2f2&_scrivito_display_mode=diff
=> Cart checkout creates an opportunity instead of a support ticket

src/Widgets/DataAttachmentsWidget/DataAttachmentsWidgetClass.ts, src/Widgets/DataAttachmentsWidget/DataAttachmentsWidgetComponent.tsx, src/Widgets/DataAttachmentsWidget/DataAttachmentsWidgetEditingConfig.ts, src/Widgets/DataIconWidget/DataIconWidgetClass.ts, src/Widgets/DataIconWidget/DataIconWidgetComponent.tsx, src/Widgets/DataIconWidget/DataIconWidgetEditingConfig.ts
Needs content: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://icon-attachment-attribute-aw.scrivito-portal-app.pages.dev/en/my-tynacoon?_scrivito_workspace_id=jf6431200f480927&_scrivito_display_mode=view
=> Icon & attachment attribute aware

src/Components/Loading.tsx, src/Objs/Product/ProductComponent.tsx, src/Objs/ProductCategory/ProductCategoryComponent.tsx, src/Widgets/DataAttachmentsWidget/DataAttachmentsWidgetComponent.tsx, src/Widgets/DataFormContainerWidget/DataFormContainerWidgetComponent.tsx, src/Widgets/DataIconWidget/DataIconWidgetComponent.tsx, src/Widgets/DataLabelWidget/DataLabelWidgetComponent.tsx, src/Widgets/DataLabelWidget/RelativeDate.tsx, src/Widgets/NavigationWidget/SubComponents/LanguageSwitch.tsx, src/utils/currentLanguage.ts, src/utils/dataValuesConfig.ts, src/utils/formatDate.ts
Makes use of the newly introduced `Scrivito.currentLanguage()`.
=> Scrivito based currentLanguage

src/Widgets/DataLabelWidget/DataLabelWidgetComponent.tsx
Cross-merge issue between https://github.com/Scrivito/scrivito-portal-app/pull/444 and https://github.com/Scrivito/scrivito-portal-app/pull/445.
=> Fix "NumberText"

src/utils/provideLocalStorageDataClass.ts
The first baby step to support search in equipment (or other data).
=> Make local storage data classes searchable

src/Widgets/AddressWidget/AddressWidgetClass.ts, src/Widgets/AddressWidget/AddressWidgetComponent.tsx, src/Widgets/AddressWidget/AddressWidgetEditingConfig.ts
Needs content: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://rip-addressformat.scrivito-portal-app.pages.dev/de?_scrivito_workspace_id=t1d41069b4741cc2&_scrivito_display_mode=diff
=> Use "currentLanguage" instead of individual "addressFormat"

src/App.tsx, src/Components/DesignAdjustments.tsx, src/Objs/Homepage/HomepageEditingConfig.ts, src/Objs/Homepage/HomepageObjClass.ts, src/assets/stylesheets/index.scss, src/assets/stylesheets/theme/box-comment.scss
This is one step to make the design also work in "flat" as well.
Needs content: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://flat-design-options.scrivito-portal-app.pages.dev/de?_scrivito_workspace_id=q6afa2eb26a9a594&_scrivito_display_mode=view
=> Homepage: Added drop shadow and rounded corners option

src/assets/stylesheets/index.scss, src/assets/stylesheets/theme/box-comment.scss
Follow up of https://github.com/Scrivito/scrivito-portal-app/pull/460.
=> [css] Two more places, that should use variable shadows

src/Data/ServiceObjectDocument/LocalStorage/localStorageServiceObjectDocumentDataClass.ts, src/Data/ServiceObjectDocument/Pisa/pisaServiceObjectDocumentDataClass.ts, src/Data/ServiceObjectDocument/ServiceObjectDocumentDataClass.ts, src/Data/ServiceObjectDocument/ServiceObjectDocumentEditingConfig.ts
https://edit-beta.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://dave-equipment-document.scrivito-portal-app.pages.dev/en/equipment-details-1e241bae572507e8?service_object_id=7681FF616BF5460FAD90A6BB5BC386B4&_scrivito_workspace_id=g8649f48024f9e2a&_scrivito_display_mode=diff
=> Add service-object document data class

src/Components/Breadcrumb.tsx, src/Objs/Homepage/HomepageEditingConfig.ts, src/Objs/Homepage/HomepageLayoutComponent.tsx, src/Objs/Homepage/HomepageObjClass.ts, src/Widgets/NavigationWidget/SubComponents/Brand.tsx, src/Widgets/NavigationWidget/SubComponents/MainNavigation.tsx, src/Widgets/NavigationWidget/SubComponents/MetaNavigation.tsx
There will soon be a better option on how to build a "portal only" website. CSS will be reused in a different PR.
=> R.I.P. sitePortalOnlyMode

src/Data/EventDocument/EventDocumentDataClass.ts, src/Data/EventDocument/EventDocumentEditingConfig.ts, src/Data/EventDocument/LocalStorage/localStorageEventDocumentDataClass.ts, src/Data/EventDocument/Pisa/pisaEventDocumentDataClass.ts
https://edit-beta.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://dave-event-documents.scrivito-portal-app.pages.dev/en/event-details-9a601c5b409e510d?event_id=4100600152A8FFCBE040007F01002CE3&_scrivito_workspace_id=kcacd8a6fbe41fac&_scrivito_display_mode=diff
=> Add event document data class

package-lock.json, package.json, src/Widgets/ColumnContainerWidget/ColumnsEditorTab.tsx
Installed via:
```
npm i -D typescript @typescript-eslint/parser @typescript-eslint/eslint-plugin @cloudflare/workers-types @types/node
```
=> Latest typescript packages

src/App.tsx, src/Components/DataBatchContext.tsx, src/Components/NotFoundErrorPage.tsx, src/Objs/Dropdown/DropdownComponent.tsx, src/Objs/Homepage/HomepageComponent.tsx, src/Objs/Homepage/HomepageLayoutComponent.tsx, src/Objs/Page/PageComponent.tsx, src/Objs/Product/ProductComponent.tsx, src/Objs/ProductCategory/ProductCategoryComponent.tsx, src/Objs/ProductsOverview/ProductsOverviewComponent.tsx, src/Objs/Redirect/RedirectComponent.tsx, src/Objs/SubnavigationOverview/SubnavigationOverviewComponent.tsx, src/assets/stylesheets/index.scss
Motivation: There might be multiple layout components rendered before the actual "main" content.
Diff best viewed without whitespace changes.
=> <main> refactoring

src/Widgets/DataAttachmentsWidget/DataAttachmentsWidgetComponent.tsx, src/Widgets/NavigationWidget/SubComponents/CurrentUserDropdown.tsx
Found by `plugin:jsx-a11y/recommended` (full integration still in progress, see future PR).
=> Fix missing alt tags

.eslintrc.json, src/Widgets/ColumnContainerWidget/ColumnsEditorTab.tsx
The only offender (`ColumnsEditorTab.tsx`) will be fixed soon.
=> Enable eslint-plugin-jsx-a11y

src/Objs/Homepage/HomepageEditingConfig.ts, src/Objs/Homepage/HomepageObjClass.ts
Follow up of https://github.com/Scrivito/scrivito-portal-app/pull/500#discussion_r1675317483.
Needs content: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://no-more-sitelogolight.scrivito-portal-app.pages.dev/en?_scrivito_workspace_id=m58c336083fed819&_scrivito_display_mode=view
=> Homepage: Removed never used "siteLogoLight"

src/Objs/defaultPageLayoutComponent.tsx
Some designs are otherwise broken.
=> Default layout: Use section for color wrapper

src/Data/Document/DocumentEditingConfig.ts
Content useful: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://scrivito-portal-app.pages.dev/de/angebotsdetails-52311cd4fb7fce3b?quote_id=18EEDF590CBA51BFE040A8C00F012317&_scrivito_workspace_id=l31c7fce1c62a0a9&_scrivito_display_mode=diff
=> Document: Allow "Body" to be selected

src/App.tsx, src/Components/ErrorBoundary.tsx, src/Objs/Product/ProductComponent.tsx, src/Objs/Redirect/RedirectComponent.tsx, src/Widgets/ColumnContainerWidget/ColumnsEditorTab.tsx, src/Widgets/TopNavigationWidget/SubComponents/CurrentUserDropdown.tsx, src/config/scrivito.ts, src/config/scrivitoSites.ts, src/main.tsx, src/scrivitoExtensions.tsx, src/utils/provideLocalStorageDataClass.ts, vite.config.ts
The basic prerendering concepts are copied from https://github.com/Scrivito/scrivito_example_app_js
=> Server-side rendering and hydration prerequisites

src/Data/CartItem/Cart.ts, src/Widgets/TopNavigationWidget/SubComponents/MetaNavigation.tsx
One small preparation to smooth the migration to `1.43.0-rc1` once available.
=> MetaNavigation: Only show cart count if available.

package-lock.json, package.json, src/Data/CartItem/Cart.ts, src/Data/Contract/Pisa/pisaContractDataClass.ts, src/Data/ContractDocument/Pisa/pisaContractDocumentDataClass.ts, src/Data/EventDocument/Pisa/pisaEventDocumentDataClass.ts, src/Data/EventRegistration/Pisa/pisaEventRegistrationDataClass.ts, src/Data/Gdpr/Pisa/pisaGdprDataClass.ts, src/Data/Opportunity/Pisa/pisaOpportunityDataClass.ts, src/Data/Order/Pisa/pisaOrderDataClass.ts, src/Data/OrderDocument/Pisa/pisaOrderDocumentDataClass.ts, src/Data/OrderRequest/Pisa/pisaOrderRequestDataClass.ts, src/Data/Quote/Pisa/pisaQuoteDataClass.ts, src/Data/QuoteDocument/Pisa/pisaQuoteDocumentDataClass.ts, src/Data/ServiceObjectDocument/Pisa/pisaServiceObjectDocumentDataClass.ts, src/Data/pisaClient.ts, src/Data/toClientParams.ts, src/Widgets/DataMessageWidget/DataMessageWidgetComponent.tsx, src/utils/provideLocalStorageDataClass.ts
There are more improvements/usage of newer APIs and feature coming. But as a start this should be already mergable.
=> Scrivito 1.43.0-rc1

src/Components/DataBatchContext.tsx, src/Components/DataErrorEditorNote.tsx, src/Widgets/DataColumnListWidget/DataColumnListWidgetComponent.tsx, src/Widgets/DataEmptyWidget/DataEmptyWidgetComponent.tsx, src/Widgets/DataPersonCardWidget/DataPersonCardWidgetComponent.tsx, src/Widgets/DataWidget/DataWidgetComponent.tsx
Recommission https://github.com/Scrivito/scrivito-portal-app/pull/431 with `scrivito` `1.43.0-rc1`.
=> Data error handling

src/Objs/Page/PageEditingConfig.ts, src/Widgets/DataAttachmentsWidget/DataAttachmentsWidgetEditingConfig.ts, src/Widgets/DataGroupWidget/DataGroupWidgetEditingConfig.ts, src/Widgets/DataIconWidget/DataIconWidgetEditingConfig.ts, src/Widgets/DataImageWidget/DataImageWidgetEditingConfig.ts, src/Widgets/DataLabelWidget/DataLabelWidgetEditingConfig.ts, src/Widgets/DataPersonCardWidget/DataPersonCardWidgetEditingConfig.ts
So far this feature is still in development and currently not shown in the UI. But in the future it will eventuell have an effect on the data selection UI.
Concept: https://docs.google.com/document/d/1B3cjqJhDaktva5PpExIucmgXXi7IRGuwZj1WwO8rMP0/edit
=> Make use of restrictDataTo

src/Data/Document/Pisa/pisaDocumentDataClass.ts, src/Data/Event/Pisa/pisaEventDataClass.ts, src/Data/ServiceObject/Pisa/pisaServiceObjectDataClass.ts
Motivated by https://github.com/Scrivito/scrivito-portal-app/pull/529#discussion_r1696630910.
=> Less custom data connections

src/Widgets/VerticalNavigationWidget/VerticalNavigationWidgetComponent.tsx
Backport of https://github.com/Scrivito/scrivito-portal-app/pull/534 to `demo4`.
=> Bugfix VerticalNavigationWidget: Consider hideInNavigation

src/assets/stylesheets/theme/fonts.scss
https://web.dev/articles/font-best-practices#choose_an_appropriate_font-display_strategy
+3 Lighthouse performance points
=> Improve font performance

src/Components/ScrivitoExtensions/SocialCardsTab.tsx, src/Objs/defaultPageEditingConfig.ts
* https://developer.x.com/en/docs/twitter-for-websites/cards/overview/abouts-cards
* https://developer.x.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image
=> Make X/Twitter Card relationship clearer

src/Widgets/DataFormContainerWidget/DataFormContainerWidgetComponent.tsx, src/Widgets/DataFormOptionsWidget/DataFormOptionsWidgetComponent.tsx
This seems to have been broken with Scrivito `1.43.0-rc1`.
With this ticket message should be able to be created again.
=> Avoid usage of useDataItem, if useData is available

.circleci/config.yml, package.json
=> Shorten "npm run check-types" to "npm run types"

src/Widgets/IconContainerWidget/IconContainerWidgetComponent.tsx
Cleanup for naming: comment [here](https://github.com/infopark/infopark_js/pull/935#discussion_r1707266250) ✌️
=> Backport: Rename icons to iconList for clarity

src/Widgets/ColumnContainerWidget/ColumnContainerWidgetComponent.tsx
=> adapted spacing

src/Components/DataBatchContext.tsx
See SDK issue #11117 for more information.
=> DataBatchContextProvider: Restart "loading" with new search term

src/Widgets/TopNavigationWidget/SubComponents/NavItem.tsx
Similar to what UtilityLink has been doing.
=> NavItem: Link directly to redirect's link if available.

src/Objs/Homepage/HomepageEditingConfig.ts, src/Objs/Homepage/HomepageObjClass.ts, src/Objs/Page/PageEditingConfig.ts, src/Objs/Page/PageObjClass.ts, src/Objs/defaultPageAttributes.ts, src/Objs/defaultPageEditingConfig.ts
Adjusted editing text as well.
=> Homepage: Allow to set "linkIcon".

src/Widgets/DataColumnListWidget/DataColumnListWidgetEditingConfig.ts, src/Widgets/DataWidget/DataWidgetEditingConfig.ts
See https://docs.google.com/document/d/1f6dgx6uuTuTJPPyt232UblXt_w7O4-7rcA-nwfGW9Fc/ .
=> Make use of "iteratesOver"

src/Components/Attachment.tsx
Best seen with a real pisa instance. Data images do not work well.
=> Attachment: On click open a new tab.

src/Widgets/ColumnContainerWidget/ColumnContainerWidgetComponent.tsx
Fixes an issue introduced in #533
=> Always render empty columns

src/assets/stylesheets/index.scss
@apepper Fixes issues https://infopark.slack.com/archives/C050WJC9YU8/p1725961180669259
=> FIX for .btn-outline-primary / secondary in active + hover state

src/Widgets/TopNavigationWidget/SubComponents/NavItem.tsx
=> Respect "Hide in navigation" in 2nd-level top navigation

src/Objs/Homepage/SiteColorsPicker.tsx
=> Try to avoid unwanted color editing

src/Components/ObjIconAndTitle.tsx, src/Widgets/VerticalNavigationWidget/VerticalNavigationWidgetClass.ts, src/Widgets/VerticalNavigationWidget/VerticalNavigationWidgetComponent.tsx, src/Widgets/VerticalNavigationWidget/VerticalNavigationWidgetEditingConfig.ts, src/assets/stylesheets/index.scss
Replaces/based on the PoC: #596
Small content update: https://edit-beta.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://dave-2nd-3rd-level-nav.scrivito-portal-app.pages.dev/en/my-tynacoon?_scrivito_workspace_id=r99902d9f7816d24&_scrivito_display_mode=diff
=> Allow 2nd and 3rd level vertical nav

src/Widgets/VerticalNavigationWidget/VerticalNavigationWidgetClass.ts, src/Widgets/VerticalNavigationWidget/VerticalNavigationWidgetComponent.tsx, src/Widgets/VerticalNavigationWidget/VerticalNavigationWidgetEditingConfig.ts
As suggested by Alex G.
Content: https://edit-beta.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://dave-optional-vertical-nav-p.scrivito-portal-app.pages.dev/en/my-tynacoon?_scrivito_workspace_id=rfa907bcbbce6622&_scrivito_display_mode=diff
=> Make parent link in vertical nav optional

src/Widgets/VideoWidget/VideoWidgetComponent.tsx, src/Widgets/VideoWidget/VideoWidgetEditingConfig.ts, src/Widgets/VideoWidget/VideoWidgetObjClass.ts, src/Widgets/VideoWidget/thumbnail.svg, src/Widgets/VideoWidget/videoPlaceholder.ts, src/assets/stylesheets/index.scss
Inspired by https://github.com/Scrivito/scrivito_example_app_js/tree/master/src/Widgets/VideoWidget
=> Add video widget

.knip.jsonc, src/Data/index.ts
=> No longer automatically load obsolete ValuesConfig* files

src/Widgets/ColumnContainerWidget/ColumnsEditorTab.tsx
Warnings where only visible in development mode (a.k.a. on localhost:8080).
=> Fix ColumnsEditorTab warnings

src/Widgets/DataIconWidget/DataIconWidgetComponent.tsx, src/Widgets/DataLabelWidget/DataLabelWidgetComponent.tsx
Adds a `<Loading />` spinner to most DataX widgets.
=> Improved DataWidget loading spinner + one Bugfix

src/Data/CallbackRequest/LocalStorage/localStorageCallbackRequestDataClass.ts, src/Data/Contract/LocalStorage/localStorageContractDataClass.ts, src/Data/ContractDocument/LocalStorage/localStorageContractDocumentDataClass.ts, src/Data/Document/LocalStorage/localStorageDocumentDataClass.ts, src/Data/Event/LocalStorage/localStorageEventDataClass.ts, src/Data/EventDocument/LocalStorage/localStorageEventDocumentDataClass.ts, src/Data/EventRegistration/LocalStorage/localStorageEventRegistrationDataClass.ts, src/Data/Gdpr/LocalStorage/localStorageGdprDataClass.ts, src/Data/Message/LocalStorage/localStorageMessageDataClass.ts, src/Data/Opportunity/LocalStorage/localStorageOpportunityDataClass.ts, src/Data/Order/LocalStorage/localStorageOrderDataClass.ts, src/Data/OrderDocument/LocalStorage/localStorageOrderDocumentDataClass.ts, src/Data/OrderRequest/LocalStorage/localStorageOrderRequestDataClass.ts, src/Data/Quote/LocalStorage/localStorageQuoteDataClass.ts, src/Data/QuoteDocument/LocalStorage/localStorageQuoteDocumentDataClass.ts, src/Data/ServiceObject/LocalStorage/localStorageServiceObjectDataClass.ts, src/Data/ServiceObjectDocument/LocalStorage/localStorageServiceObjectDocumentDataClass.ts, src/Data/Subscription/SubscriptionEditingConfig.ts, src/Data/Ticket/LocalStorage/localStorageTicketDataClass.ts, src/Data/User/LocalStorage/localStorageUserDataClass.ts
With #11262 (coming with `1.45.0`) this will no longer be allowed.
=> Remove `_id` from schema

src/Widgets/VerticalNavigationWidget/VerticalNavigationWidgetComponent.tsx
* Non-active paths close on nav
* Active paths open on nav
* Remove support for following the hierarchy without closing or scrolling
=> Update usability of vertical nav

src/Widgets/HeadlineWidget/HeadlineWidgetClass.ts, src/Widgets/HeadlineWidget/HeadlineWidgetEditingConfig.ts, src/assets/stylesheets/index.scss
Allows to keep the styling of a heading, but remove it from the semantic hierarchy.
=> Headline with level div.

src/Widgets/DataAttachmentsWidget/DataAttachmentsWidgetComponent.tsx, src/Widgets/DataIconWidget/DataIconWidgetComponent.tsx, src/Widgets/DownloadCardWidget/DownloadCardWidgetComponent.tsx, src/Widgets/TopNavigationWidget/SubComponents/MetaNavigation.tsx, src/assets/stylesheets/index.scss, src/assets/stylesheets/theme/attachment.scss
Cherry-picks most stuff from https://github.com/Scrivito/scrivito-portal-app/pull/632 except for the primary/secondary color change.
With that the count of "axe" is reduced from 18 to 3 issues.
=> Small color contrast improvements

src/Data/Order/LocalStorage/localStorageOrderDataClass.ts, src/Data/Quote/LocalStorage/localStorageQuoteDataClass.ts
PisaSales has this already in their schema.
=> Quote and Order: Added new "url" attribute

src/Data/CartItem/Cart.ts, src/Data/CartItem/CartItemDataClass.ts, src/Data/CartItem/CartItemEditingConfig.ts, src/Data/provideLocalStorageDataClass.ts, src/Data/types.ts
Needs content: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://cart-reference.scrivito-portal-app.pages.dev/en/cart-a8ede3121df9e2f6?_scrivito_workspace_id=n35dbe1f47caf0ad&_scrivito_display_mode=view
Renamed `productId` to `product`. If someone still has some items in their cart left, the cart checkout page will not be able to display the products properly and will not be able to post an opportunity.
=> Cart: Now officially reference a product

src/Widgets/CardWidget/CardWidgetComponent.tsx, src/Widgets/IconContainerWidget/IconContainerWidgetComponent.tsx, src/Widgets/TickListWidget/TickListWidget.scss, src/assets/stylesheets/index.scss
Fixes Issue
https://infopark.slack.com/archives/C050WJC9YU8/p1727089632703809
See in WC "🌈all the colors!1!🌈"
=> bg-transparent works in cards + color fixes

src/Widgets/ColumnContainerWidget/ColumnContainerWidgetClass.ts, src/Widgets/ColumnContainerWidget/ColumnContainerWidgetComponent.tsx, src/Widgets/ColumnContainerWidget/ColumnContainerWidgetEditingConfig.ts, src/Widgets/ColumnContainerWidget/ColumnsEditorTab.scss, src/Widgets/ColumnContainerWidget/ColumnsEditorTab.tsx, src/assets/stylesheets/scrivitoExtensions.scss
Allows to toggle "Show gutters?" for grid mode. For Flex mode is currently disabled.
https://github.com/user-attachments/assets/372df704-a68d-4e35-a1ba-66bed708ee60
=> Column widget: Show gutters option

src/Data/CallbackRequest/Pisa/pisaCallbackRequestDataClass.ts, src/Data/User/UserDataClass.ts, src/Data/provideLocalStorageDataClass.ts, src/Data/types.ts
Refactored `types.ts` to be more in line with types directly defined in Scrivito.
=> Vanilla scrivito types

src/Widgets/SearchResultsWidget/SearchResultsWidgetComponent.tsx
It is already addressed since #403.
=> SearchResultsWidget: Remove obsolete TODO

src/config/scrivito.ts
See https://www.scrivito.com/scrivito-js-sdk-1-45-0-released-a5629242c79fb89a#activateDataIntegration for details
=> Scrivito.configure({ activateDataIntegration: true })

src/Widgets/DataMessageWidget/DataMessageWidgetComponent.tsx
=> DataMessageWidget: Bugfix user read.

src/Objs/Homepage/HomepageObjClass.ts
Expected value: `identifier:number`, where identifier can have `-`, e.g. `portal-app:5`.
This will hopefully help with future content versions.
Needs content:
* https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://contentformat.scrivito-portal-app.pages.dev/de?_scrivito_workspace_id=hdc1d0ad13e39fd9&_scrivito_display_mode=view
* https://edit.scrivito.com/6d226c03f32a8ea4e8ae8e5cbe6c6e2c~https://demo5.scrivito-portal-app.pages.dev/6d226c03f32a8ea4e8ae8e5cbe6c6e2c/de?_scrivito_workspace_id=jd2b308378a4837a&_scrivito_display_mode=view
Content adjusted with the following js console command (on each language version):
```js
Scrivito.Obj.root().update({ contentFormat: 'portal-app:5' })
```
=> Homepage: Added hidden "contentFormat" attribute

src/App.tsx, src/assets/stylesheets/index.scss
See https://trello.com/c/yYYQej2A/106-fix-footer-to-the-end-of-the-page for details.
Broken since https://github.com/Scrivito/scrivito-portal-app/pull/485.
=> Design: Fix footer issue.

src/assets/stylesheets/index.scss
=> Fix for footer to the end of the page

index.html, src/prerenderContent/generateHtml.ts, src/prerenderContent/prerenderObj.tsx
This will be useful for e.g. defining fonts using javascript.
=> Prerendering: Support <style> tag of helmet.

src/Components/customToastify.css, src/assets/stylesheets/index.scss
Motivation: In the near future I want to provide a different `jr-headline-font-family` on request.
=> [design] Refactor "Fira Sans" into var(--jr-headline-font-family)

src/Widgets/SectionWidget/SectionWidgetComponent.tsx
Copied from https://github.com/Scrivito/scrivito_example_app_js/blob/5929d12aef58dacf468232b16379a2ed9721e943/src/Components/Navigation.js#L42
=> Play background video as intended on mobile Safari

src/Components/NotFoundErrorPage.tsx
The readme stays as is for now.
=> No longer use the term CMS in front facing UI

src/config/scrivitoSites.ts
Introduced in https://github.com/Scrivito/scrivito-portal-app/pull/708.
=> Bugfix in ensureSiteIsPresent: Handle multitenancy correctly.

.circleci/config.yml
Follow up of https://github.com/Scrivito/scrivito-portal-app/pull/679/files#r1888049253.
=> [circle] Cleaner environment setting

.github/copilot-instructions.md
For more details see https://docs.github.com/en/copilot/customizing-copilot/adding-custom-instructions-for-github-copilot
=> Added copilot-instructions with prettier rules

src/Data/CartItem/Cart.ts, src/Objs/Product/ProductComponent.tsx, src/Widgets/DataDeleteButtonWidget/DataDeleteButtonWidgetComponent.tsx, src/Widgets/DataFormContainerWidget/DataFormContainerWidgetComponent.tsx
Needs content: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://unified-delete-message2.scrivito-portal-app.pages.dev/en/event-details-9a601c5b409e510d?_scrivito_workspace_id=jcaad25e77966228&_scrivito_display_mode=diff
Inspired by https://github.com/Scrivito/scrivito-portal-app/pull/721#discussion_r1904216192.
=> Unified delete message (again)

.knip.jsonc, eslint.config.mjs, src/Components/ScrivitoExtensions/SocialCardsTab.tsx, src/Data/CartItem/Cart.ts, src/Data/CurrentUser/CurrentUserDataItem.ts, src/Data/provideLocalStorageDataClass.ts, src/Widgets/ColumnContainerWidget/ColumnsEditorTab.tsx, src/Widgets/DataFormInputFieldWidget/DataFormInputFieldWidgetComponent.tsx, src/Widgets/DataSearchWidget/DataSearchWidgetClass.ts, src/Widgets/DataSearchWidget/DataSearchWidgetEditingConfig.ts, src/Widgets/VideoWidget/VideoWidgetComponent.tsx, src/config/scrivitoSites.ts, src/prerenderContent/getSiteIds.ts, src/prerenderContent/reportError.ts, src/utils/blobToBinary.ts, src/utils/fileToDataUrl.ts, src/utils/pisaDataBinaryToUrl.ts
Some of the code changes were actual issues discovered thanks to the new rule.
=> Enable template expression type check

src/Widgets/TopNavigationWidget/SubComponents/Brand.tsx, src/Widgets/TopNavigationWidget/TopNavigationWidgetClass.ts, src/Widgets/TopNavigationWidget/TopNavigationWidgetComponent.tsx, src/Widgets/TopNavigationWidget/TopNavigationWidgetEditingConfig.ts
Defaults to `root` (as previously).
=> TopNavigationWidget: Allow to configure brand link

src/Data/CurrentUser/CurrentUserDataEditingConfig.ts, src/Data/CurrentUser/CurrentUserDataItem.ts, src/Data/GeneralMarketingConsent/GeneralMarketingConsentDataItem.ts, src/Data/GeneralMarketingConsent/GeneralMarketingConsentEditingConfig.ts
DataClasses are already localized. With `1.47.0` this can now also be done for DataItems.
=> DataItem localized attributes

src/assets/stylesheets/index.scss
Trello: https://trello.com/c/Dxauu8uF/108-fix-color-issue-of-selected-color
=> selection color more accessible

src/Widgets/SliderWidget/SliderWidgetComponent.tsx, src/assets/stylesheets/index.scss
regarding bg-color in current slide
=> adaptions for prev/next nav and indicator

src/Widgets/DataSearchWidget/DataSearchWidgetClass.ts, src/Widgets/DataSearchWidget/DataSearchWidgetComponent.tsx, src/Widgets/DataSearchWidget/DataSearchWidgetEditingConfig.ts
This is a preparation for ContentSearchResult.
=> DataSearch: Allow to set a button label

src/Data/Subscription/SubscriptionDataClass.ts
Limit is already handled directly by Scrivito.
Closes #755.
=> Subscription: Complain about unsupported params

src/Widgets/DataImageWidget/DataImageWidgetComponent.tsx, src/Widgets/ImageWidget/ImageWidgetComponent.tsx
See https://github.com/Scrivito/scrivito-portal-app/pull/762#discussion_r1961704769
=> Only apply cover if height is set

src/Widgets/SliderWidget/SliderWidgetClass.ts, src/Widgets/SliderWidget/SliderWidgetComponent.tsx, src/Widgets/SliderWidget/SliderWidgetEditingConfig.ts
Previously it was hardcoded to 5 seconds.
Needs content: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://slider-duration.scrivito-portal-app.pages.dev/en?_scrivito_workspace_id=ud8f8d872a34c34e&_scrivito_display_mode=diff
=> SliderWidget: Added autoplayInterval option

src/Components/NotFoundErrorPage.tsx
Incorporates feedback from https://scrivito-portal-app.pages.dev/eb1881e746534c8bb5ae231834a64257​
=> Remove GetStartedButton

src/Widgets/CheckoutButtonWidget/CheckoutButtonWidgetComponent.tsx
See https://github.com/Scrivito/scrivito-portal-app/pull/748#discussion_r1988829240
=> Prevent checking out the cart while inputs are invalid

src/Data/CurrentUser/CurrentUserDataItem.ts, src/Data/CurrentUser/fetchWhoAmIWithToken.ts, src/Data/CurrentUser/verifySameWhoAmIUser.ts
=> Translate JWT error messages

src/config/scrivito.ts, src/main.tsx, src/privateJrPlatform/Components/WrongContentFormat.tsx, src/privateJrPlatform/getJrPlatformApp.ts, src/privateJrPlatform/getJrPlatformConfig.ts, vite.config.ts
Concept: https://docs.google.com/document/d/1qF_jeawRCV4wVeE0f-E3A9jeGRX6AKvX7GhG53qiFys/
Also provides new JrPlatform flag and initial content URL.
=> Verify content format

src/Objs/Product/ProductComponent.tsx, src/Widgets/DataFormNumberWidget/DataFormNumberWidgetComponent.tsx, src/assets/stylesheets/index.scss
fixes for 
https://trello.com/c/x3TDfokO/109-improve-styling-of-product-quantity
=> design fixes in contrast and responsive on product page

src/Data/localStorageDataConnection.ts, src/config/scrivito.ts, src/config/scrivitoSites.ts, src/config/scrivitoTenants.ts, src/privateJrPlatform/Components/MissingTenant.tsx, src/privateJrPlatform/getJrPlatformApp.ts, src/privateJrPlatform/multiTenancy.ts, vite.config.ts
+ Add alias lookup.
One goal of this PR: Incoporated https://github.com/Scrivito/scrivito-portal-app/compare/main...v5 into `main`.
=> JR Platform: Extract multi tenancy

src/Widgets/TopNavigationWidget/SubComponents/LanguageSwitch.tsx
=> Capitalize language labels

src/assets/stylesheets/vendor/bs5/mixins/_banner.scss
See [1] and [2] for details.
[1] https://github.com/twbs/bootstrap/releases/tag/v5.3.5
[2] https://github.com/twbs/bootstrap/pull/41347
=> Bootstrap 5.3.5

src/Components/Attachment.tsx, src/Widgets/DataFormUploadWidget/DataFormUploadWidgetComponent.tsx, src/assets/stylesheets/index.scss
Design from Alex from https://github.com/Scrivito/scrivito-portal-app/pull/822.
=> DataFormUploadWidget: Allow to add more files

src/Data/CallbackRequest/callbackRequestParamsFallback.ts, src/Data/CartItem/Cart.ts, src/Data/CartItem/CartItemDataClass.ts, src/Data/ContentSearchResult/ContentSearchResultDataClass.ts, src/Data/Contract/contractParamsFallback.ts, src/Data/ContractDocument/contractDocumentParamsFallback.ts, src/Data/CurrentUser/CurrentUserDataItem.ts, src/Data/CurrentUser/verifySameWhoAmIUser.ts, src/Data/Document/documentParamsFallback.ts, src/Data/Event/eventParamsFallback.ts, src/Data/EventDocument/eventDocumentParamsFallback.ts, src/Data/EventRegistration/eventRegistrationParamsFallback.ts, src/Data/Gdpr/gdprParamsFallback.ts, src/Data/GeneralMarketingConsent/GeneralMarketingConsentDataItem.ts, src/Data/Message/messageParamsFallback.ts, src/Data/Opportunity/opportunityParamsFallback.ts, src/Data/Order/orderParamsFallback.ts, src/Data/OrderDocument/orderDocumentParamsFallback.ts, src/Data/OrderRequest/orderRequestParamsFallback.ts, src/Data/Quote/quoteParamsFallback.ts, src/Data/QuoteDocument/quoteDocumentParamsFallback.ts, src/Data/ServiceObject/serviceObjectParamsFallback.ts, src/Data/ServiceObjectDocument/serviceObjectDocumentParamsFallback.ts, src/Data/Subscription/SubscriptionDataClass.ts, src/Data/Ticket/ticketParamsFallback.ts, src/Data/User/userParamsFallback.ts, src/Data/localStorageDataConnection.ts, src/config/scrivitoSites.ts
This is a preparation for using Honeybadger.
How to test:
* Run localhost app with `PRIVATE_JR_PLATFORM=true`
* Visit http://localhost:8080/ - a "The tenant ID is missing." error is clearly visible
* Open the JS console.
With this PR:
* No error message within the JS console.
=> Less error reports

src/Data/CurrentUser/CurrentUserDataItem.ts, src/Data/CurrentUser/notifyOnConnectionTimeout.tsx, src/Data/notifyOnConnectionTimeout.tsx
Shows a timeout toast after 5 seconds. Toast disappears, if connection gets established later.
=> Timeout notification for PisaSales

src/Objs/Homepage/HomepageEditingConfig.ts, src/Objs/Homepage/HomepageObjClass.ts
Follow up of https://github.com/Scrivito/scrivito-portal-app/pull/859.
=> Homepage: Removed obsolete "pisaUrl".

src/Widgets/DataLabelWidget/DataLabelWidgetEditingConfig.ts
Follow up of https://github.com/Scrivito/scrivito-portal-app/pull/866.
=> DataLabel: Fixed new description of `date` option

src/assets/stylesheets/vendor/bs5/mixins/_banner.scss, src/assets/stylesheets/vendor/bs5/mixins/_box-shadow.scss, src/assets/stylesheets/vendor/bs5/tests/mixins/_box-shadow.test.scss
https://blog.getbootstrap.com/2025/06/17/bootstrap-5-3-7/
=> Bootstrap version 5.3.7

src/Data/CurrentUser/verifySameWhoAmIUser.ts, src/Data/Gdpr/GdprDataClass.ts, src/Data/localStorageDataConnection.ts, src/Data/pisaClient.ts
Follow up of https://github.com/Scrivito/scrivito-portal-app/pull/890.
=> Remove more workarounds

src/Components/ScrivitoExtensions/SiteBorderRadiusEditor.tsx, src/Objs/Homepage/HomepageEditingConfig.ts
Follow up of https://github.com/Scrivito/scrivito-portal-app/pull/900.
=> Homepage: Improve names of site groups

src/Widgets/TopNavigationWidget/SubComponents/LanguageSwitch.tsx, src/config/scrivitoSites.ts
Follow-up for https://github.com/Scrivito/scrivito-portal-app/pull/907#discussion_r2242176317
* Three queries less than in main after 907
* Two queries less than in main before 907
=> Optimize search queries

src/Components/ImageOrVideo.scss, src/Components/ImageOrVideo.tsx, src/Widgets/CardWidget/CardWidgetComponent.tsx, src/Widgets/SectionWidget/SectionWidgetComponent.tsx, src/Widgets/SliderWidget/SliderWidgetComponent.tsx
Also auto-stop on "prefers-reduced-motion".
Backport of https://github.com/Scrivito/scrivito-portal-app/pull/904 to `main`.
[Concept](https://docs.google.com/document/d/1q4RqsL8alSl34ulBr2WRdOhKJMfQtz-fFnzSRXYp4fY/edit?tab=t.0#heading=h.gyss5p15hl8)
https://github.com/user-attachments/assets/42dac7a6-aadf-4b25-a125-9abe5e3f32f8
=> ImageOrVideo: Pause autoplay video on click (main)

src/config/configureErrorReporting.ts
This should help debugging, e.g. for issues such as https://app.honeybadger.io/projects/132043/faults/122720430
=> Error reporting: Add information about the workspace id

src/Widgets/SliderWidget/SliderWidget.scss
https://sass-lang.com/documentation/breaking-changes/mixed-decls/
=> Fix SASS deprecation warning

src/Objs/Page/PageEditingConfig.ts
Inspired by https://github.com/Scrivito/scrivito-portal-app/pull/944.
=> Page: Add empty Section as initial content
