src/Widgets/ColumnContainerWidget/ColumnContainerWidgetEditingConfig.ts
src/Widgets/ColumnContainerWidget/ColumnsEditorTab.scss
src/Widgets/ColumnContainerWidget/ColumnsEditorTab.tsx

Before:
After:
Thanks to @agessler for the design!

disableResponsiveAdaption now part of ColumnsEditorTab

---

.github/dependabot.yml

FYI If I understand the docs correctly we could also configure Dependabot to inform us about major updates independently from the weekly check by configuring [`groups.update-types`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups) instead of ignoring them globally.

Weekly Dependabot ignores major updates

---

.github/dependabot.yml

Inspired by https://github.blog/changelog/2021-05-21-dependabot-version-updates-can-now-ignore-major-minor-patch-releases/

Dependabot: Create one PR per major update

---

package-lock.json
package.json

with bootstrap 5.2
Avoids https://app.circleci.com/pipelines/github/Scrivito/scrivito-portal-app/509/workflows/151a0c89-1d84-4d24-af6d-8a083e201a54/jobs/1303?invite=true#step-103-106_89

Downgrade sass to avoid deprecation warnings

---

src/Widgets/DataFormContainerWidget/DataFormContainerWidgetComponent.tsx

This allows to reuse a form to send multiple message, when staying on the same page. E.g. when inside of a footer of #227.

DataFormContainer: Reset a form after submit (create only)

---

src/Widgets/DataListWidget/DataListWidgetClass.ts
src/Widgets/DataListWidget/DataListWidgetComponent.tsx
src/Widgets/DataListWidget/DataListWidgetEditingConfig.ts

Adds an option to show a footer for a data list widget. This allows to e.g. add a data form to push items to the data list widget list.

DataListWidget: Allow to show footer

---

.github/dependabot.yml

Once a week is too much noise for me.
I did not find a good way to delay "major" updates for e.g. a week or a month. Thoughts?

Run dependabot only once a month

---

src/Widgets/DataAttachmentsWidget/DataAttachmentsWidgetComponent.tsx

Introduced in https://github.com/Scrivito/scrivito-portal-app/pull/304.

DataAttachmentsWidget bugfix: isFullBinaryArray no longer loops itself.

---

src/Widgets/DataListWidget/DataListWidgetClass.ts
src/Widgets/DataListWidget/DataListWidgetComponent.tsx

As outlined before the goal is, to only set a datalocator either on the page or in a "DataGroupWidget". All other widgets should _not_ (for now) define a datalocator.
Live preview: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://drop-datalocator.scrivito-portal-app.pages.dev/my-tynacoon?_scrivito_workspace_id=lad559fcb11b188b&_scrivito_display_mode=view

DataListWidget: Drop datalocator

---

src/Widgets/DataLabelWidget/DataLabelWidgetClass.ts
src/Widgets/DataLabelWidget/DataLabelWidgetComponent.tsx
src/Widgets/DataLabelWidget/DataLabelWidgetEditingConfig.ts
src/Widgets/DataLabelWidget/RelativeDate.tsx
src/utils/formatDate.ts

Allows to format a date value as "Date and time" and "Only date". "Relative" was previously already available.
Needs content: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://datalabelwidget-date.scrivito-portal-app.pages.dev/my-tynacoon?_scrivito_workspace_id=mc2dbbd39b44e23a&_scrivito_display_mode=view

DataLabelWidget: More date options

---

src/Widgets/DataFormContainerWidget/DataFormContainerWidgetComponent.tsx
src/Widgets/DataFormSubmitButtonWidget/DataFormSubmitButtonWidgetComponent.tsx

E.g. clicking on the submit button propagates to an upper link, if the propagation is not stopped.
Follow-up of https://github.com/Scrivito/scrivito-portal-app/pull/332#discussion_r1527621580.
Example Content (**not to be published!**): https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://dataformcontainer-bugfix.scrivito-portal-app.pages.dev/events-fb302b23c46fea41?_scrivito_workspace_id=v667419e005c44b6&_scrivito_display_mode=view

DataFormContainer: Work properly inside of links

---

src/Widgets/DataPersonCardWidget/DataPersonCardWidgetClass.ts
src/Widgets/DataPersonCardWidget/DataPersonCardWidgetComponent.tsx
src/Widgets/DataPersonCardWidget/DataPersonCardWidgetEditingConfig.ts

It's better to leave this to a regular HeadlineWidget with all its options.
Needs content - please also check the event details page: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://simpler-datapersoncardwidget.scrivito-portal-app.pages.dev/my-tynacoon?_scrivito_workspace_id=p81a8ca32bdb5135&_scrivito_display_mode=view

Remove Headline from DataPersonCardWidget

---

src/config/scrivito.ts
src/config/scrivitoSites.ts

Assumptions/constraints:
* Each site has a unique homepage `_language`
* If no site matches the current URL, the first site by language code is the fallback site
* The language prefix is always used, even if there is only one site
* The language detection ignores a multi-tenancy path prefix, no matter if multi-tenant or not
I.e. `<origin>/<tenantId>/<lang><path>` or `<origin>/<lang><path>`

Multi-language basics

---

src/config/scrivitoSites.ts

Reverts `SCRIVITO_PORTAL_APP_ROOT_CONTENT_ID` and `baseUrl` attribute consideration in `scrivitoSites.ts` (as introduced in #388).
Also improves `siteForUrl`.
Closes #389, since this is a different approach to the issue (dropping the functionality).

Partly baseUrl

---

src/Widgets/ColumnContainerWidget/ColumnsEditorTab.scss
src/assets/stylesheets/scrivitoExtensions.scss

**mixed untouched (no dark adaptions)**
**current mixed (old dark adaptions)**
**new adaptions**
Should be merged when Scrivito Dark Mode is live...

new dark UI colors and adaptions for column editor

---

src/Components/Loading.tsx
src/Widgets/DataColumnListWidget/DataColumnListWidgetComponent.tsx
src/Widgets/DataEmptyWidget/DataEmptyWidgetComponent.tsx
src/Widgets/DataPersonCardWidget/DataPersonCardWidgetComponent.tsx
src/Widgets/DataWidget/DataWidgetComponent.tsx

PR best viewed with whitespace off.
The main purpose is to indicate temporary issues connecting to backends.
As far as I can see we don't have any means of detecting permanent issues, because both known error cases
* PisaSales backend not available (TypeError)
* Not authorized as a user (status 401)
are transparently handled (retried) by the SDK.
One way we could provide more info to the user could be a pessimistic guess:
Add a timeout to the loader component and switch to some form of "Sorry, try again later" message.

Show loading indicator for data widgets

---

src/assets/stylesheets/index.scss

The order is open to further refinement, but at least it's no longer completely off.
Maybe unifying the menu item style on mobile is more important as a next step?

Mobile menu order improvements

---

src/Widgets/DataPersonCardWidget/DataPersonCardWidgetClass.ts
src/Widgets/DataPersonCardWidget/DataPersonCardWidgetComponent.tsx
src/Widgets/DataPersonCardWidget/DataPersonCardWidgetEditingConfig.ts

This also has the advantage that no headline is shown, if the user could not be found.
Needs content: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://workaround-datapersoncardwid.scrivito-portal-app.pages.dev/en/my-tynacoon?_scrivito_workspace_id=je9ba13d7a074d63&_scrivito_display_mode=view

DataPersonCard: Calculate user differently

---

src/Widgets/SearchResultsWidget/SearchResultsWidgetClass.ts
src/Widgets/SearchResultsWidget/SearchResultsWidgetComponent.tsx
src/Widgets/SearchResultsWidget/SearchResultsWidgetEditingConfig.ts

For that the loading of "search.count()" had to move to "TotalCountSummary"
Needs content: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://more-loading.scrivito-portal-app.pages.dev/en/search-results?q=Foo&_scrivito_workspace_id=k05aba3b533fa47f&_scrivito_display_mode=view

SearchResultsWidget shows loader for "results count"

---

src/Objs/Product/ProductComponent.tsx
vite.config.ts

When the user is not yet logged in, the "Add to cart button" now becomes a "log in" button.

"Add to cart" button becomes "log in" button

---

src/assets/stylesheets/index.scss

Enables ` hyphens: auto` for all text. This way the navigation will not strangely "wrap".
Before: 
After:
Live-Preview: https://hyphens.scrivito-portal-app.pages.dev/en

Enable hyphens to break words

---

src/config/scrivito.ts
src/main.tsx

Navigating inside Scrivito Extensions may break them for the latest Scrivito version.

Only redirect in the app, not in extensions

---

src/Components/DataBatchContext.tsx

Avoids potentially inaccurate "dataScope.count()" function. It also potentially uses less requests.
Since scrivito internally first requests one item and then uses the continuation with another 10 items and a continuation `.take({ limit: limit + 1})` can be responded directly from the already loaded data.

DataBatchContext: Improve "hasMore"

---

.eslintrc.json
package-lock.json
package.json
src/Components/DataBinaryImage.tsx

https://www.npmjs.com/package/@arabasta/eslint-plugin-require-useeffect-dependency-array
This takes away one degree of freedom but
this is virtually never used and most likely an error. See, for example, #264.
Feel free to close if the added complexity is not worth it. The endless loop was a logic mistake in the first place and there's no reliable way to prevent it. We always executed the effect (no dependency array) and always set a state in the callback.

Enforce passing a dependency array to useEffect

---

src/Widgets/DataLabelWidget/DataLabelWidgetComponent.tsx

Formats a numbers attribute according to the language of a site. To test you could use the `size` attribute of a Document.

DataLabelWidget: Format numbers language aware

---

src/Data/pisaClient.ts
src/Objs/Homepage/HomepageEditingConfig.ts
src/Objs/Homepage/HomepageObjClass.ts
src/utils/pisaDataBinaryToUrl.ts
vite.config.ts

Instead of hardcoding the pisa endpoint, the endpoint is now read out from the content of the default homepage. This allows to run multiple instance much easier, since no app adjustments are needed anymore.
The "pisaUrl" content has already been set on the "golden master" tenant.
Still open todos:

Pisa url from content

---

src/Components/ScrivitoExtensions/SocialCardsTab.scss
src/Components/ScrivitoExtensions/SocialCardsTab.tsx

This is something that caught my attention building #461.
The social cards relied on undocumented CSS classes from the Scrivito namespace.
I think there are potentially more clashes with the Scrivito namespace but the font use was most obvious.

Social cards no longer rely on unofficial SDK font

---

src/Widgets/NavigationWidget/NavigationWidgetClass.ts
src/Widgets/NavigationWidget/NavigationWidgetComponent.tsx
src/Widgets/NavigationWidget/NavigationWidgetEditingConfig.ts
src/Widgets/NavigationWidget/SubComponents/CurrentUserDropdown.tsx
src/Widgets/NavigationWidget/SubComponents/MainNavigation.tsx
src/Widgets/NavigationWidget/SubComponents/SearchBox.tsx

If I'm not mistaken this was the only remaining place, where we did "label translation" content based. It was a bit in the way (see https://github.com/Scrivito/scrivito-portal-app/pull/478#discussion_r1660754517), so I switched it to "always translate using the app".
Needs content: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://localize-navigation-via-app.scrivito-portal-app.pages.dev/de?_scrivito_workspace_id=q3e3e8b37d9c5a75&_scrivito_display_mode=diff

Localize navigation via app

---

src/Widgets/ColumnContainerWidget/ColumnsEditorTab.tsx

Adding columns, either by choosing a larger preset or by using the "+" button, lead to `content` being `undefined` under certain conditions. The SDK requires a `Widget[]` and throws an error:
```
ArgumentError: Unexpected value undefined for attribute "content". Expected: An array of Widget instances.
```

Fix a bug when adding columns

---

design/author-detail.html
design/error.html
design/event-detail.html
design/events.html
design/my-tynacoon-slim-nav.html
design/my-tynacoon.html
design/newsroom-detail.html
design/newsroom.html
design/order-detail.html
design/order-overview.html
design/product-detail.html
design/products-filter-detail.html
design/products-filter.html
design/products-overview.html
design/profile.html
design/sales-detail.html
design/search.html
design/ticket-detail.html
src/Components/ErrorBoundary.tsx
src/Objs/Product/ProductComponent.tsx
src/Objs/ProductCategory/ProductCategoryComponent.tsx
src/Objs/ProductsOverview/ProductOverviewLayoutComponent.tsx
src/Widgets/SearchResultsWidget/SearchResultsWidgetComponent.tsx
src/Widgets/SectionWidget/SectionWidgetComponent.tsx

There are only two types of sections: One with padding (`py-5`) and one "without" padding (`py-2`). This allows me to use the SectionWidget as is (after this PR) for layout components like current page title or breadcrumbs.
AFAIK we currently have no `SectionWidget` with `showPadding` set to `false` in our Scrivito content.

Normalize padding

---

src/Widgets/BreadcrumbWidget/BreadcrumbWidgetClass.ts
src/Widgets/BreadcrumbWidget/BreadcrumbWidgetComponent.tsx
src/Widgets/BreadcrumbWidget/BreadcrumbWidgetEditingConfig.ts

To be later used in layoutHeader to replace hardcoded `<Breadcrumb />` in SubnavigationOverviewLayout and ProductOverviewLayout.
Thumbnail will be added later.

BreadcrumbWidget

---

src/Components/ModalSpinner.tsx
src/Components/Submitting.tsx
src/Widgets/CheckoutButtonWidget/CheckoutButtonWidgetComponent.tsx
src/Widgets/DataFormContainerWidget/DataFormContainerWidgetComponent.tsx

See https://github.com/Scrivito/scrivito-portal-app/pull/494#discussion_r1668561059
For now, the visuals are a bit more intrusive (dark overlay) compared to what we had before.
Depending on the overlay appearance we choose, we could consider getting rid of styling forms (`form-loading`) and buttons (`disabled`) differently while submitting.
We use a hidden dialog b/c a dialog background apparently can't be made transparent.

Full-screen submit indicator

---

src/Data/Contract/Pisa/pisaContractDataClass.ts
src/Data/ContractDocument/Pisa/pisaContractDocumentDataClass.ts
src/Data/EventDocument/Pisa/pisaEventDocumentDataClass.ts
src/Data/EventRegistration/Pisa/pisaEventRegistrationDataClass.ts
src/Data/Gdpr/Pisa/pisaGdprDataClass.ts
src/Data/Opportunity/Pisa/pisaOpportunityDataClass.ts
src/Data/Order/Pisa/pisaOrderDataClass.ts
src/Data/OrderDocument/Pisa/pisaOrderDocumentDataClass.ts
src/Data/OrderRequest/Pisa/pisaOrderRequestDataClass.ts
src/Data/Quote/Pisa/pisaQuoteDataClass.ts
src/Data/QuoteDocument/Pisa/pisaQuoteDocumentDataClass.ts
src/Data/ServiceObjectDocument/Pisa/pisaServiceObjectDocumentDataClass.ts
src/Data/pisaClient.ts

See https://github.com/infopark/scrivito_js/pull/11025
https://infopark.slack.com/archives/G01F5J9817Z/p1720631421230469
/cc @patrykboch

[OnDevSdk] Adapt to new API for `provideDataClass({ restApi })`

---

src/Data/ServiceObjectDocument/ServiceObjectDocumentEditingConfig.ts

The term "equipment" is used in the visitor presentation layer only. Here, we're at the backend data layer.

Fix ServiceObjectDocument editing config labels

---

src/config/scrivitoSites.ts
vite.config.ts

In order to inform the app about the default site and its language versions, a new optional env `SCRIVITO_ROOT_CONTENT_ID` is added.
In order to work properly in a multi-site instance with isolated sites, root pages must have a `baseUrl` set.
Isolated sites (or language versions) which share a URL prefix with another site/version don't work yet, e.g.,
```
https://example.com/en
https://example.com/en-US
```

Extend multi-site config to allow for isolated sites

---

src/config/scrivitoSites.ts

Todo from #518
Also added support for xx-XX language codes for language versions.
I ignored the sort performance assuming the number of sites is smallish and the callback is not called frequently.

Handle ambiguous base URLs

---

src/Data/CallbackRequest/Pisa/pisaCallbackRequestDataClass.ts

With Scrivito 1.43.0-rc1 errors in coonection.index will be thrown again.

Bugfix CallbackRequest: If no callback can be found return empty string

---

src/Widgets/DataDeleteButtonWidget/DataDeleteButtonWidgetComponent.tsx
src/Widgets/DataFormBooleanWidget/DataFormBooleanWidgetComponent.tsx
src/Widgets/DataFormInputFieldWidget/DataFormInputFieldWidgetComponent.tsx
src/Widgets/DataFormNumberWidget/DataFormNumberWidgetComponent.tsx
src/Widgets/DataMessageWidget/DataMessageWidgetComponent.tsx

useDataItem() might not return the most "top" item on the stack, if there is e.g. a "DataScope" on top of the stack. "useData()" will always return the newest thing on top of the stack, e.g. a "dataItem" or a "dataScope".
Follow up of https://github.com/Scrivito/scrivito-portal-app/pull/547.

Replace useDataItem() with useData().dataItem()

---

src/Widgets/DataFormNumberWidget/DataFormNumberWidgetComponent.tsx

DataFormNumberWidget: Use bootstrap styling for input field

---

.circleci/config.yml

Otherwise some package will complain, that they are not compatible.
Avoids "Unsupported engine" warnings, such as https://app.circleci.com/pipelines/github/Scrivito/scrivito-portal-app/1709/workflows/67bed7bd-0d09-4639-bfde-8061eacc69be/jobs/5272?invite=true#step-102-0_40

[circle] Use node version 18.18.

---

src/Data/pisaClient.ts
src/Objs/Homepage/HomepageEditingConfig.ts
src/config/scrivitoSites.ts
vite.config.ts

Instead of `SCRIVITO_ROOT_CONTENT_ID` we now configure `SCRIVITO_ROOT_OBJ_ID`. This allows to infer both
* the default site ID and
* the root content ID
from the obj, which was not possible the other way around.
This makes it easier to integrate the app into existing instances that already use the site ID `default`.

Drop hardcoded site ID "default"

---

src/Data/Contract/ContractDataClass.ts
src/Data/ContractDocument/ContractDocumentDataClass.ts
src/Data/CurrentUser/CurrentUserDataItem.ts
src/Data/Event/EventDataClass.ts
src/Data/EventDocument/EventDocumentDataClass.ts
src/Data/EventRegistration/EventRegistrationDataClass.ts
src/Data/Message/MessageDataClass.ts
src/Data/Order/OrderDataClass.ts
src/Data/OrderDocument/OrderDocumentDataClass.ts
src/Data/OrderRequest/OrderRequestDataClass.ts
src/Data/Quote/QuoteDataClass.ts
src/Data/QuoteDocument/QuoteDocumentDataClass.ts
src/Data/ServiceObject/ServiceObjectDataClass.ts
src/Data/ServiceObjectDocument/ServiceObjectDocumentDataClass.ts
src/Data/Ticket/TicketDataClass.ts

It does not work properly. E.g. if an attribute is empty (null) the SDK automatically converts this to an empty string ("") and then complains, that an empty string is not a valid ID.

Data: Drop "string" attribute workaround

---

src/config/scrivitoSites.ts

* we configure `baseUrl: 'stringlist'`, thus
* the SDK will never return a `link` or `linklist` (even if this is stored as such on another site)
* the new simplified logic still supports `string` thanks to `autoConvertAttributes: true`
Line 72 could alternatively read `if (!Array.isArray(baseUrl)) return []`. I kept the current version to make switching to `string` easier. Maybe YAGNI but we need a check for type safety anyway.

Simplify base URL logic

---

src/Widgets/TopNavigationWidget/TopNavigationWidget.scss
src/Widgets/TopNavigationWidget/TopNavigationWidgetComponent.tsx
src/assets/stylesheets/index.scss

The previous position-based selectors caused two issues:
* The logo did not overlap if the nav header had a section below the top nav
* All sections in the top nav had a grey bar
Apart from not matching sections that are not actual top-nav sections, the selector matches exactly as before, including the landing page layout and slim nav. Not fully sure if this is intended, but it worked before and still works.

Top nav selector fixes

---

src/Objs/Homepage/SiteColorsPicker.scss
src/assets/stylesheets/scrivitoExtensions.scss

This also prevents scrollbars if the OS is set to always show scrollbars. If the gutter is wider than the padding a row will have x-overflow.
Reported here: https://infopark.slack.com/archives/C05FSSUAKUP/p1723627150805279

Harmonize spacing in sidebar extensions

---

src/assets/stylesheets/index.scss

The 1st commit fixes SVG icons with unknown dimensions:
---
The 2nd commit fixes the slim nav for icons with a large height. It looks interesting but because we don't have the flap background as in the full nav I assume this was not intended:

Brand logo size improvements

---

src/utils/blobToBinary.ts

> Moreover, blob.type is generally reliable only for common file types like images, HTML documents, audio and video. Uncommon file extensions would return an empty string.
Source: https://developer.mozilla.org/en-US/docs/Web/API/Blob/type
Discovered by accidentally picking the a pixelmator file instead of the exported image.

blobToBase64: Bugfix unknown blob type data

---

package-lock.json
package.json
src/Components/Attachment.tsx
src/Widgets/DataAttachmentsWidget/DataAttachmentsWidgetComponent.tsx
src/Widgets/DataFormUploadWidget/DataFormUploadWidgetComponent.tsx
src/assets/stylesheets/index.scss
src/assets/stylesheets/theme/attachment.scss
src/utils/dataBinaryToUrl.ts
src/utils/fileToDataUrl.ts

Allow to drag 'n' drop files on the screen.
Also show a preview of the selected files:
Last, but not least, limit the files to max. 50 MB:

DataFormUploadWidget: Drag 'n' drop, preview and file size limit

---

src/Data/CurrentUser/errorToast.tsx
src/Data/pisaClient.ts
src/Widgets/CheckoutButtonWidget/CheckoutButtonWidgetComponent.tsx
src/Widgets/DataFormContainerWidget/DataFormContainerWidgetComponent.tsx
src/prerenderContent/reportError.ts
src/utils/provideLocalStorageDataClass.ts

https://github.com/Scrivito/scrivito-portal-app/pull/589 already provided a bugfix for a specific issue.
The issue could be reproduced, by trying to upload https://drive.google.com/file/d/1t5KUq5yxc9wYqNUI4FDm4yNsr3ukyR0z/view?usp=sharing (this can still be done in the PR). Since prior to https://github.com/Scrivito/scrivito-portal-app/pull/589 the mime type did not match and an error was passed to the `rejected` callback of the promise. This error message was shown in a `toast.error`.
But since the error message was quite long (~3 mb) it crashed the react rendering resulting in an endless "spinner".
This PR prevents the endless "spinner" by limiting the length of string passed to the `toast.error`. You still can't upload the file in this PR, but you will see an error message and be able …

Bugfix: Errors during data form submission no longer freeze the app

---

src/config/scrivitoSites.ts

We fall back to look at non-app-related sites only as a last resort.
This is not a plain refactoring. At least the behavior in the empty-content case has changed.

Optimize multi-site helpers

---

src/App.tsx
src/Components/NotFoundErrorPage.tsx
src/config/scrivitoSites.ts

This PR tries to solve two issue:
* If the tenant in question has no scrivito portal content site show an error
* If the root for the `NotFoundErrorPage` can't be found due to not being logged in - log the user in. This allows for root pages to be protected content.

Protected root

---

src/Widgets/VideoWidget/VideoWidget.scss
src/Widgets/VideoWidget/VideoWidgetComponent.tsx
src/Widgets/VideoWidget/VideoWidgetEditingConfig.ts
src/Widgets/VideoWidget/VideoWidgetObjClass.ts
src/Widgets/VideoWidget/videoPlaceholder.ts

* On par with Youtube and Vimeo widget
* Editors don't have to care about poster image size

Add aspect ratio to video widget

---

src/Data/CurrentUser/CurrentUserDataItem.ts

A newer version of PisaSales might no longer transmit attributes with empty values such as `null` or `''`.

Make WhoAmI more liberal (allow undefined values)

---

.eslintrc.json
src/Components/ScrivitoExtensions/SocialCardsTab.tsx
src/Objs/Product/ProductComponent.tsx
src/Widgets/SearchResultsWidget/SearchResultsWidgetComponent.tsx

With this all `ImageTag` in our code-base should have an alt tag now.
Discovered with:
```
npx @axe-core/cli https://scrivito-portal-app.pages.dev/en/plug-in-nozzle-0-3mm-6eff94f91196a7d4 --tags wcag2a --load-delay=500 --exit
```
The other complained is addressed in https://github.com/Scrivito/scrivito-portal-app/pull/629.

Accessibility: Add more "alt" tags + eslint rule

---

src/Components/Loading.tsx
src/Widgets/DataFormOptionsWidget/DataFormOptionsWidgetComponent.tsx

I made sure a form with a required enum can't be sent.
There are two other widgets using `useEnumOptions` (DataIconWidget and DataLabelWidget), but every instance of these is used inside data or detail pages, so their loading behavior already matches how the rest of the page behaves.

Show a spinner for not-yet-loaded options

---

.lighthouserc.yml

Thanks to improved content we no longer see "The heading structure is not logically nested."

lighthouse: Increase accessibility score

---

src/config/scrivitoSites.ts

Otherwise hash links like https://scrivito-portal-app.pages.dev/en#ecoline will not work. With this PR it works (see https://siteforurl-ignores-hash-and.scrivito-portal-app.pages.dev/en#ecoline).

siteForUrl: Bugfix - ignore query and search from input URL

---

src/Data/User/UserDataClass.ts

Prior to this change the situation was this:
* Neoletter profile service allows to set an arbitrary `salutation` - any string such as "Ms.", "Mr.", "Frau", "Herr" or even other strings such as "Master of the universe" can be set by the user itself.
* PisaSales uses an enum value for salutation, e.g. "F" or "M".
If we merge the salutation of neoletter's my profile service with the salutation of the current user in PisaSales "users" Scrivito will rightfully complain with:
```
Expected attribute "salutation" of data class "User" to be one of ["M","F","ME","FE","MS","FS","MSP","FSP","MF","FF"], but got "Herr"
```
To avoid this situation, this PR no longer merges the salutation of the current user into the user, but leaves the "salutation" data to the value as provided by PisaSales.

User: Ignore salutation of current user

---

src/Data/ServiceObject/LocalStorage/localStorageServiceObjectDataClass.ts
src/Data/ServiceObject/Pisa/pisaServiceObjectDataClass.ts
src/Data/fetchAttributes.ts
src/Data/provideLocalStorageDataClass.ts

This allows to set arbitrary values for parentId, e.g. the string `'null'`. With this PisaSales will only return service objects, that don't have a parent object. See #11367 for more details.
Needs content: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://filter-parentid.scrivito-portal-app.pages.dev/en/equipment?_scrivito_workspace_id=q85ff08c54c0e147&_scrivito_display_mode=view

Filter `parentId` from service object attributes

---

src/assets/stylesheets/index.scss

How to reproduce (all in Safari):
* Visit https://scrivito-portal-app.pages.dev/de
* Adjust the window width
Expected: The logo always uses the correct amount of space (especially the width).
Actual: Sometimes the white area around the logo would be much larger then expected.
Now repeat with https://bugfix-safari-navigation-gli.scrivito-portal-app.pages.dev/de to see if this PR fixes it (at least for me it does).
Kudos to @agessler for finding the fix!

Safari design glitch fix

---

src/Components/NotFoundErrorPage.tsx

Adds a "Get started with your CMS" button if the given tenant is empty. A visit to that link with automatically initialize the content for the tenant.

NotFoundErrorPage: Added get started button

---

src/Data/ServiceObject/Pisa/pisaServiceObjectDataClass.ts

Without this function wrapping "fetchAttributes" would directly be calling PisaSales and as a consequence enforce a login - even for a user that is just visiting the homepage.
The bug was introduced in https://github.com/Scrivito/scrivito-portal-app/pull/681.

ServiceObject: Bugfix fetching attributes

---

src/config/scrivitoSites.ts

This leads to better fallbacks for outdated/legacy permalinks, e.g.,
* https://example.com/contact -> https://example.com/en/contact (instead of https://example.com/en)
* https://example.com/en-US/contact -> https://example.com/en/contact (instead of https://example.com/en)

Keep URL path if falling back to the default site

---

src/Objs/Product/ProductComponent.tsx
src/Widgets/DataDeleteButtonWidget/DataDeleteButtonWidgetComponent.tsx

Needs content: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://unified-delete-message.scrivito-portal-app.pages.dev/en/cart-a8ede3121df9e2f6?_scrivito_workspace_id=ub67fc762303f1b1&_scrivito_display_mode=diff
Please note, that the content is only visible, if one adds some products to the cart.
How to reproduce:
* Add a product to the cart via the product page
* Remove a product from the cart via the product page
* Add the product again to the cart (via the product page)
* Switch to the cart
* Remove the product again from the cart (via the cart page)
Before:
Now:
Found while reviewing https://github.com/Scrivito/scrivito-portal-app/pull/720.

Unified delete message

---

src/Data/provideLocalStorageDataClass.ts

This is a preparation of the upcoming CRM search.
Intended use https://github.com/Scrivito/scrivito-portal-app/compare/searchLocalStorageDataClasses...poc_crm_search . 
Example deployment: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://poc-crm-search.scrivito-portal-app.pages.dev/en/search-02fffe06aa9f09d9?_scrivito_workspace_id=p6d384dda43ac613&_scrivito_display_mode=view

searchLocalStorageDataClasses

---

vite.config.ts

See https://v3.vitejs.dev/guide/build.html#chunking-strategy
I picked a chunking strategy where we chunk two large groups of vendor dependencies: React based and Scrivito based packages.

Restore original Vite chunk size limit

---

src/Widgets/DataImageWidget/DataImageWidgetComponent.tsx

E.g. `image: ['reference', { title: 'Image', to: 'Image' }]`
This is a preparation for `ContentSearchResult`.

DataImageWidget: Allow attributeValue to be a DataItem

---

src/Data/ContentSearchResult/ContentSearchResultDataClass.ts
src/Data/localStorageDataConnection.ts
src/Widgets/SearchResultsWidget/SearchResult.tsx
src/Widgets/SearchResultsWidget/SearchResultsWidgetComponent.tsx

Moves search logic of https://github.com/Scrivito/scrivito-portal-app/blob/main/src/Widgets/SearchResultsWidget/SearchResultsWidgetComponent.tsx into a data class. Overall goal: Get rid of `SearchResultsWidget` and use data search primitives.
Working copy to test it out: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://contentsearchresult.scrivito-portal-app.pages.dev/en/search-results?q=Test&_scrivito_workspace_id=r228d708e9d6524d&_scrivito_display_mode=view
Please not that other PRs are still needed before the content can go live.

ContentSearchResult

---

src/Components/DataBatchContext.tsx
src/Widgets/DataColumnListWidget/DataColumnListWidgetComponent.tsx
src/Widgets/DataWidget/CombinedLoader.tsx
src/Widgets/DataWidget/DataBatchLoadingIndicator.tsx
src/Widgets/DataWidget/DataWidgetComponent.tsx

Motivation: When someone clicks on "Load more" a spinner should be shown until all informations are available (more items in the load and the status of "hasMore").
See effect by artificially slowing down `localStorageDataConnection#index`:
```ts
await new Promise((resolve) => setTimeout(resolve, 1500))
```

Search improvements + better loader

---

src/Widgets/SectionWidget/SectionWidgetComponent.tsx
src/Widgets/SliderWidget/SliderWidgetComponent.tsx

Fixes #767.
As far as I can see, if one changes the `src` of the `<source>` dom element, the browser (at least Chromium) will ignore this `<source>` and pretend that it does not exist.
With the explicit `key` we tell React to recreate a new `<video>` dom element, if the content URL or it type changes.
It is also a better solution for #4767 (in Scrivito)

Rerender <source> elements on change

---

src/Objs/Dropdown/DropdownComponent.tsx
src/Objs/Dropdown/DropdownObjClass.ts
src/utils/getMetadata.ts

Only for regular visitors, not editors.
Motivation: Don't train users that the auto-redirect URLs work.

Dropdown: Show 404 instead of redirect

---

src/Widgets/BreadcrumbWidget/BreadcrumbWidgetComponent.tsx
src/Widgets/SectionWidget/SectionWidgetComponent.tsx

Needs content: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://section-real-no-padding.scrivito-portal-app.pages.dev/en?_scrivito_workspace_id=i9e9de05e0394f78&_scrivito_display_mode=diff
Previously some padding was added, but is now in the way, e.g. for modern landing pages.

SectionWidget: !showPadding => no padding

---

src/Data/ContentSearchResult/ContentSearchResultDataClass.ts
src/Objs/ProductCategory/ProductCategoryEditingConfig.ts
src/Objs/ProductCategory/ProductCategoryObjClass.ts
src/Objs/defaultPageAttributes.ts
src/Objs/defaultPageEditingConfig.tsx
src/Widgets/SearchResultsWidget/SearchResult.tsx
src/utils/getMetadata.ts

`metaDataDescription` was originally introduced in https://github.com/Scrivito/scrivito_example_app_js/commit/a9f29d18b011be82630bd8c7e55ebb18f517f370#diff-6f02b4692074b5c3984b8d01f9bc00693e47e6185df112d8e5524dcc6e8420a9R3. But the name is quite old and can be simplified. Requested by Kris. Since there are not many places, that use `metaDataDescription` I think this is a good request.
Needs content: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://rip-meta-data-description.scrivito-portal-app.pages.dev/en/my-profile?_scrivito_workspace_id=ubbd3298f18c6b0f&_scrivito_display_mode=diff

metaDataDescription => description

---

src/Data/Gdpr/GdprDataClass.ts

Filter is too complex to implement, but the rest is mostly "pass on".
Needs content: https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://gdpr-support-sorting.scrivito-portal-app.pages.dev/en/gdpr-consent-form?_scrivito_workspace_id=qb34eb88398ae576&_scrivito_display_mode=view

Gdpr: tokenAuthorization based supports search, count and order

---

src/Data/CurrentUser/fetchWhoAmIWithToken.ts

An error could look like this:
```
Access to fetch at 'https://example.com/portal/whoami' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
This is the case if - for example - the PisaSales server is not running.

fetchWhoAmIWithToken: Catch CORS policy errors

---

src/Widgets/SliderWidget/SliderWidget.scss

Avoid white background when scrolling different-height slides

---

src/privateJrPlatform/Components/WrongContentFormat.tsx

Improved message e.g. for tenant `9d40fdf1b7bce0f07d83086580be796d`.

WrongContentFormat: Improve error message

---

src/assets/stylesheets/index.scss
src/assets/stylesheets/scrivitoEditing.scss

This avoids uneven text alignment and loading alignment flashes

Make all language icons equal width

---

package-lock.json
package.json

The newer version broke local development. It's not yet clear, why. Downgrading for now.

[npm] Downgrade @vitejs/plugin-react-swc

---

.knip.jsonc
src/config/configureErrorReporting.ts
src/honeybadgerStub.ts
vite.config.ts

This way boot time exceptions are also reliably logged to Honeybadger.
The stub is provided to reduce payload, if Honeybadger is not needed.

Include Honeybadger right away

---

.knip.jsonc
src/Data/DataSearchResult/DataSearchResultDataClass.ts
src/Data/DataSearchResult/dataSearchResultIndexFallback.ts
src/Data/DataSearchResult/getDataItemUrl.ts
src/Data/DataSearchResult/loadDataItemUrl.ts

Content to review the changes - https://edit.scrivito.com/d0a154d76edf2a7bd991fc658e700a1d~https://data-search-result.scrivito-portal-app.pages.dev/en/search-results?q=Tynacoon&_scrivito_workspace_id=p6d384dda43ac613&_scrivito_display_mode=view
⚠️ Do not publish the working copy yet ⚠️!
The goal of this PR is to add `DataSearchResult` similar to the existing `ContentSearchResult`. For that the API of https://docs.google.com/document/d/1sIxmlC5BuQouu5TKZMwrdG6R-6Mrs4w57GQiymvTJ8U/edit?tab=t.0#heading=h.7zv8ou23o8xp is implemented.

DataSearchResult

---

src/Widgets/CardWidget/CardWidgetComponent.tsx

Next try, after https://github.com/Scrivito/scrivito-portal-app/pull/864 did not work properly.
Bootstrap requires, that "card-footer" is a direct child of "card-footer" to be correctly aligned (at the bottom).
Previously this only worked, if _no_ link was set. Now it always works, independent of the link.
How to reproduce:
1. Have a Data Column Widget with multiple data items
2. Place a Card Widget within the data column.
3. Add something within the card, e.g. a static image
4. Enable the "Show footer" option of the card widget
5. In the now available footer add a DataLabelWidget and select an attribute. Ideally the attribute should have varying length, so that it sometimes needs one line and sometimes two lines.
Expected (now with this commit): The DataLabelWidget is always "bottom …

CardWidget: Bugfix styling of footer, if link is set

---

_scrivito_extensions.html
src/Components/ScrivitoExtensions/SocialCardsTab.scss
src/assets/stylesheets/index.scss
src/assets/stylesheets/scrivitoEditing.scss

Fixes https://github.com/infopark/scrivito_js/issues/11903.
Custom colors and fonts are currently not used in the widget library.

Fix widget library styling

---

src/Widgets/PageTitleWidget/PageTitleWidgetComponent.tsx

Most PageTitleWidgets will be placed at the very top of the page. Therefore a h1 is quite fitting. Styling is not affected.

PageTitleWidget: Use level h1

---

src/Widgets/CardWidget/CardWidgetComponent.tsx
src/Widgets/CardWidget/CardWidgetEditingConfig.ts
src/Widgets/DataCountWidget/DataCountWidgetEditingConfig.ts
src/Widgets/DataSearchWidget/DataSearchWidgetEditingConfig.ts
src/Widgets/HeadlineWidget/HeadlineWidgetClass.ts
src/Widgets/HeadlineWidget/HeadlineWidgetComponent.tsx
src/Widgets/HeadlineWidget/HeadlineWidgetEditingConfig.ts
src/Widgets/SliderWidget/SliderWidgetEditingConfig.ts
src/assets/stylesheets/index.scss

[Concept](https://docs.google.com/document/d/1q4RqsL8alSl34ulBr2WRdOhKJMfQtz-fFnzSRXYp4fY/edit?tab=t.0#heading=h.raifs2th3xnv).
Since the data class changes needs to be approved independently this PR is only send to energy during the vacation season.
TODO for the `main` merge:

Margin-Setting for Headline Widget

---

src/Components/NotFoundErrorPage.tsx
src/Objs/Homepage/HomepageEditingConfig.ts
src/config/scrivitoSites.ts
src/main.tsx
src/multiSite/ensureSiteIsPresent.ts
src/multiSite/extractFromUrl.ts
src/multiSite/instanceBaseUrl.ts
src/multiSite/isNoSitePresent.ts
src/privateJrPlatform/isJrPlatformValidContentFormat.ts
src/privateJrPlatform/multiTenancy.ts

It is pretty hard to keep the many possible URL formats and fallbacks in mind when changing the code.
Maybe we can come up with a better code structure in a follow-up. I've identified at least these responsibilities
- Known URL schemes and their precedence (including multi-tenancy, content-ID-based, default site, via baseUrl)
- Recognizing sites
- Redirecting to fallback URLs

Support multi-site in addition to multi-language

---

src/privateJrPlatform/getJrPlatformConfig.ts

Once we get clearance for the content it can move to `v6-content` as well.

Use energy-content for now

---

src/multiSite/ensureSiteIsPresent.ts

Follow up of https://github.com/Scrivito/scrivito-portal-app/pull/907.
It will be normalized by the SDK in the next step anyway.
How to reproduce:
* Visit https://main.scrivito-portal-app.pages.dev/ and look at the address bar
* For a brief moment the website visits `/en/` to rewrite that back to `/en`
With this branch:
* Visit https://reduce-url-rewrite.scrivito-portal-app.pages.dev/ and look at the address bar
* The website will directly rewrite to `/en`.

redirectToSiteUrl: Remove trailing / from path

---

src/Components/ImageOrVideo.tsx
src/Widgets/CardWidget/CardWidgetClass.ts
src/Widgets/CardWidget/CardWidgetComponent.tsx
src/Widgets/CardWidget/CardWidgetEditingConfig.ts
src/Widgets/SectionWidget/SectionWidgetComponent.tsx
src/Widgets/SliderWidget/SliderWidgetComponent.tsx

Backgrounds of `CardWidget` can now also be a video:
[Concept](https://docs.google.com/document/d/1q4RqsL8alSl34ulBr2WRdOhKJMfQtz-fFnzSRXYp4fY/edit?tab=t.0#heading=h.d1qjg5rpzwfl)
Backport of https://github.com/Scrivito/scrivito-portal-app/pull/898 to `main`.

CardWidget allows video background (main)

---

src/Objs/Homepage/HomepageEditingConfig.ts
src/assets/stylesheets/index.scss

@agessler I took the liberty to widen the panic flap (as long as no logo has been set):
| Before | After |
| -- | -- |
|  <img width="1042" height="514" alt="image" src="https://github.com/user-attachments/assets/8d4c9f2f-7b54-44b6-a078-2a2bbe743885" /> |  <img width="1042" height="514" alt="image" src="https://github.com/user-attachments/assets/ce982250-76ca-4249-86f4-44a6efcdc000" />|

Initialize new homepages with minimal content
